/* REPUESTOS IA CLOUD v2.0 — inventario remoto, offline-first, fotografia/OCR y Excel. */
(()=>{'use strict';
const C=window.REPUESTOS_CONFIG||{},STORE='repuestos-ia-records-v2',PFX=C.recordPrefix||'inventory_';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],iso=()=>new Date().toISOString(),uid=()=>crypto.randomUUID();
const state={route:'home',previous:'home',partId:null,photo:null,syncing:false,filter:''};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const recs=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return[]}};
const persist=a=>localStorage.setItem(STORE,JSON.stringify(a));
const byType=t=>recs().filter(x=>x.type===t),part=id=>byType('part').find(x=>x.id===id);
const day=(v=Date.now())=>{const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fmt=v=>v?new Date(v).toLocaleString('es-CL',{dateStyle:'short',timeStyle:'short',hour12:false}):'—';
const money=v=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(v)||0);
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,2800)}
function status(t,k=''){const e=$('#sync-state');if(!e)return;e.textContent=t;e.style.background=k==='ok'?'#17865b55':k==='warn'?'#b9770055':'#ffffff18'}
function upsert(x){const a=recs(),i=a.findIndex(y=>y.id===x.id);x.updatedAt=iso();x.dirty=true;x.synced=false;i<0?a.push(x):a[i]=x;persist(a);syncSoon();return x}
function add(type,title,data){return upsert({id:uid(),type,title,data,at:iso(),updatedAt:iso(),dirty:true,synced:false})}
function syncSoon(){clearTimeout(syncSoon.t);syncSoon.t=setTimeout(sync,700)}
async function sync(){if(state.syncing)return;if(!navigator.onLine){status('Offline · guardado local','warn');return}if(C.requireAuth!==false&&!window.REPUESTOS_AUTH?.token()){status('Acceso pendiente','warn');return}state.syncing=true;status('Sincronizando…');try{let a=recs();for(const x of a.filter(r=>r.dirty)){const row={id:x.id,record_type:PFX+x.type,payload:{...x,dirty:false,synced:true,app:'repuestos_ia'},occurred_at:x.at};const r=await fetch(`${C.supabaseUrl}/rest/v1/${C.table}?on_conflict=id`,{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)});if(!r.ok)throw Error(await r.text());x.dirty=false;x.synced=true}persist(a);const r=await fetch(`${C.supabaseUrl}/rest/v1/${C.table}?select=payload&record_type=like.${PFX}*&order=occurred_at.asc`);if(!r.ok)throw Error(await r.text());const remote=await r.json(),map=new Map(recs().map(x=>[x.id,x]));for(const row of remote){const n=row.payload,o=map.get(n?.id);if(!n||n.app!=='repuestos_ia')continue;if(!o||(!o.dirty&&new Date(n.updatedAt||n.at)>=new Date(o.updatedAt||o.at)))map.set(n.id,{...n,dirty:false,synced:true})}persist([...map.values()]);status('Nube sincronizada','ok');render()}catch(e){console.warn(e);status('Pendiente nube','warn')}finally{state.syncing=false}}
function stockFor(id){return byType('move').filter(x=>x.data.partId===id).reduce((n,m)=>n+(['entrada','ajuste+'].includes(m.data.kind)?Number(m.data.qty):['salida','ajuste-'].includes(m.data.kind)?-Number(m.data.qty):0),0)}
const lowParts=()=>byType('part').filter(p=>stockFor(p.id)<=Number(p.data.min||0));
const valueAll=()=>byType('part').reduce((n,p)=>n+stockFor(p.id)*Number(p.data.unitCost||0),0);
const movesToday=()=>byType('move').filter(m=>day(m.at)===day());
const badge=(t,k='')=>`<span class="badge ${k}">${esc(t)}</span>`,empty=t=>`<div class="empty">${esc(t)}</div>`;
function go(route,ctx={}){state.previous=state.route;state.route=route;Object.assign(state,ctx);state.photo=null;render();scrollTo(0,0)}
function partItem(p){const s=stockFor(p.id),min=Number(p.data.min||0);return `<button class="list-item" data-part="${p.id}"><div class="line"><div><b>${esc(p.data.code)}</b> · ${esc(p.data.name)}</div>${badge(String(s),s<=min?'red':'green')}</div><div class="meta">P/N ${esc(p.data.partNumber||'—')} · ${esc(p.data.warehouse||'Sin bodega')} / ${esc(p.data.location||'Sin ubicación')} · mínimo ${min}</div></button>`}
function home(){const parts=byType('part'),low=lowParts();return `<section class="hero"><span class="eyebrow">Inventario remoto · ${esc(C.supervisor)}</span><h1>Control de repuestos</h1><p>Celular y computador trabajando sobre la misma nube desde cualquier lugar.</p></section><div class="grid stats"><div class="card stat"><small>Repuestos</small><b>${parts.length}</b></div><div class="card stat"><small>Stock crítico</small><b class="${low.length?'kpi-bad':'kpi-good'}">${low.length}</b></div><div class="card stat"><small>Movimientos hoy</small><b>${movesToday().length}</b></div><div class="card stat"><small>Valor inventario</small><b style="font-size:18px">${money(valueAll())}</b></div></div><h2>Acciones rápidas</h2><div class="grid actions"><button class="quick" data-go="part_new"><b>＋</b>Nuevo repuesto</button><button class="quick" data-go="move"><b>⇄</b>Entrada / salida</button><button class="quick" data-go="capture"><b>📷</b>Captura IA</button><button class="quick" data-go="reports"><b>▤</b>Excel diario</button></div><h2>Alertas de reposición</h2><div class="list">${low.length?low.slice(0,8).map(partItem).join(''):empty('No existen repuestos bajo mínimo.')}</div>`}
function parts(){const q=state.filter.toLowerCase(),a=byType('part').filter(p=>!q||JSON.stringify(p.data).toLowerCase().includes(q));return `<div class="line"><h1>Repuestos</h1><button class="primary" data-go="part_new">Nuevo</button></div><label>Buscar<input id="search" placeholder="Código, P/N, descripción, equipo, ubicación…" value="${esc(state.filter)}"></label><div class="list" style="margin-top:12px">${a.length?a.map(partItem).join(''):empty('No hay repuestos registrados.')}</div>`}
function partForm(){return `<span class="eyebrow">Alta de repuesto</span><h1>Nuevo repuesto</h1><form id="part-form"><div class="formgrid"><label>Código interno<input name="code" required></label><label>Número de parte<input name="partNumber"></label></div><label>Descripción / nombre<input name="name" required></label><div class="formgrid"><label>Marca<input name="brand"></label><label>Equipo / familia<input name="equipment"></label><label>Bodega<input name="warehouse"></label><label>Ubicación<input name="location" placeholder="Estante / rack / nivel"></label><label>Stock mínimo<input name="min" type="number" min="0" value="1"></label><label>Stock máximo<input name="max" type="number" min="0" value="5"></label><label>Stock inicial<input name="initial" type="number" min="0" value="0"></label><label>Costo unitario CLP<input name="unitCost" type="number" min="0" step="1" value="0"></label></div><label>Criticidad<select name="criticality"><option>Normal</option><option>Alta</option><option>Crítica</option></select></label><label>Proveedor<input name="supplier"></label><div class="button-row"><button type="button" class="outline" data-camera>📷 Tomar foto</button><button type="button" class="outline" data-gallery>Adjuntar foto</button><button type="button" class="outline" id="ocr-btn">IA/OCR leer etiqueta</button></div><div id="photo-preview">${state.photo?`<img class="photo" src="${state.photo}">`:''}</div><div id="ocr-result" class="callout" hidden></div><button class="primary">Guardar repuesto</button></form>`}
function detail(){const p=part(state.partId);if(!p)return empty('Repuesto no encontrado.');const s=stockFor(p.id),m=byType('move').filter(x=>x.data.partId===p.id).sort((a,b)=>new Date(b.at)-new Date(a.at));return `<div class="line"><div><span class="eyebrow">${esc(p.data.code)}</span><h1>${esc(p.data.name)}</h1></div>${badge('Stock '+s,s<=Number(p.data.min||0)?'red':'green')}</div>${p.data.photo?`<img class="photo" src="${p.data.photo}">`:''}<div class="grid stats"><div class="card"><small>P/N</small><b>${esc(p.data.partNumber||'—')}</b></div><div class="card"><small>Ubicación</small><b>${esc(p.data.warehouse||'—')} / ${esc(p.data.location||'—')}</b></div><div class="card"><small>Valor stock</small><b>${money(s*Number(p.data.unitCost||0))}</b></div><div class="card"><small>Reposición sugerida</small><b>${Math.max(0,Number(p.data.max||0)-s)}</b></div></div><button class="primary" data-move-part="${p.id}">Registrar movimiento</button><h2>Historial</h2><div class="list">${m.length?m.map(x=>`<div class="list-item"><div class="line"><b>${esc(x.data.kind.toUpperCase())} · ${x.data.qty}</b><span>${fmt(x.at)}</span></div><div class="meta">OT ${esc(x.data.ot||'—')} · Equipo ${esc(x.data.equipment||'—')} · ${esc(x.data.note||'')}</div>${x.data.photo?`<img class="photo" src="${x.data.photo}">`:''}</div>`).join(''):empty('Sin movimientos.')}</div>`}
function moveForm(){const opts=byType('part').map(p=>`<option value="${p.id}" ${state.partId===p.id?'selected':''}>${esc(p.data.code)} · ${esc(p.data.name)} · stock ${stockFor(p.id)}</option>`).join('');return `<span class="eyebrow">Trazabilidad</span><h1>Movimiento de stock</h1><form id="move-form"><label>Repuesto<select name="partId" required><option value="">Seleccionar…</option>${opts}</select></label><div class="formgrid"><label>Tipo<select name="kind"><option value="entrada">Entrada</option><option value="salida">Salida</option><option value="ajuste+">Ajuste +</option><option value="ajuste-">Ajuste -</option></select></label><label>Cantidad<input name="qty" type="number" min="0.01" step="0.01" required></label><label>OT / documento<input name="ot"></label><label>Equipo / TAG<input name="equipment"></label><label>Solicitante / responsable<input name="person"></label><label>Área / destino<input name="area"></label></div><label>Observación<textarea name="note"></textarea></label><div class="button-row"><button type="button" class="outline" data-camera>📷 Evidencia</button><button type="button" class="outline" data-gallery>Adjuntar</button></div><div id="photo-preview">${state.photo?`<img class="photo" src="${state.photo}">`:''}</div><button class="primary">Confirmar movimiento</button></form>`}
function capture(){return `<span class="eyebrow">Asistente visual</span><h1>Captura IA desde celular</h1><div class="panel"><p>Tome una fotografía de la etiqueta o empaque. El OCR propondrá código, número de parte y descripción para revisión antes de guardar.</p><div class="button-row"><button class="primary" data-camera>📷 Tomar fotografía</button><button class="outline" data-gallery>Elegir fotografía</button></div><div id="photo-preview">${state.photo?`<img class="photo" src="${state.photo}">`:''}</div><div style="margin-top:12px"><button id="capture-analyze" class="primary" ${state.photo?'':'disabled'}>Analizar y crear ficha</button></div><div id="ocr-result" class="callout" hidden></div></div>`}
function dailyRows(){return movesToday().map(m=>{const p=part(m.data.partId);return{Fecha:fmt(m.at),Tipo:m.data.kind,Codigo:p?.data.code||'',NumeroParte:p?.data.partNumber||'',Repuesto:p?.data.name||'',Cantidad:Number(m.data.qty),StockActual:p?stockFor(p.id):'',OT:m.data.ot||'',Equipo:m.data.equipment||'',Responsable:m.data.person||'',Area:m.data.area||'',Observacion:m.data.note||''}})}
function exportDaily(){if(!window.XLSX)return toast('Excel no disponible');const d=day(),rows=dailyRows(),stock=byType('part').map(p=>({Codigo:p.data.code,NumeroParte:p.data.partNumber||'',Repuesto:p.data.name,Marca:p.data.brand||'',Bodega:p.data.warehouse||'',Ubicacion:p.data.location||'',Stock:stockFor(p.id),Minimo:Number(p.data.min||0),Maximo:Number(p.data.max||0),Criticidad:p.data.criticality||'',CostoUnitario:Number(p.data.unitCost||0),ValorStock:stockFor(p.id)*Number(p.data.unitCost||0)})),crit=lowParts().map(p=>({Codigo:p.data.code,Repuesto:p.data.name,Stock:stockFor(p.id),Minimo:Number(p.data.min||0),ReposicionSugerida:Math.max(0,Number(p.data.max||0)-stockFor(p.id))})),wb=XLSX.utils.book_new(),sum=[{Indicador:'Fecha',Valor:d},{Indicador:'Movimientos',Valor:rows.length},{Indicador:'Repuestos catalogados',Valor:byType('part').length},{Indicador:'Stock crítico',Valor:crit.length},{Indicador:'Valor inventario CLP',Valor:valueAll()}];XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(sum),'RESUMEN');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'MOVIMIENTOS');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(stock),'INVENTARIO');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(crit),'STOCK CRITICO');XLSX.writeFile(wb,`REPORTE_DIARIO_REPUESTOS_${d}.xlsx`);add('report','Reporte diario '+d,{date:d,count:rows.length,critical:crit.length,value:valueAll()});toast('Excel diario generado')}
function reports(){const m=byType('move').sort((a,b)=>new Date(b.at)-new Date(a.at));return `<h1>Centro de reportes</h1><div class="grid stats"><div class="card stat"><small>Movimientos hoy</small><b>${movesToday().length}</b></div><div class="card stat"><small>Entradas hoy</small><b>${movesToday().filter(x=>x.data.kind==='entrada').length}</b></div><div class="card stat"><small>Salidas hoy</small><b>${movesToday().filter(x=>x.data.kind==='salida').length}</b></div><div class="card stat"><small>Críticos</small><b>${lowParts().length}</b></div></div><div class="panel"><h2 style="margin-top:0">Excel diario</h2><p>Incluye Resumen, Movimientos, Inventario valorizado y Stock crítico.</p><button id="excel-daily" class="primary">Descargar Excel de hoy</button></div><h2>Últimos movimientos</h2><div class="tablewrap"><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Repuesto</th><th>Cant.</th><th>OT</th><th>Equipo</th></tr></thead><tbody>${m.slice(0,100).map(x=>{const p=part(x.data.partId);return `<tr><td>${fmt(x.at)}</td><td>${esc(x.data.kind)}</td><td>${esc(p?.data.code||'')} ${esc(p?.data.name||'')}</td><td>${x.data.qty}</td><td>${esc(x.data.ot||'')}</td><td>${esc(x.data.equipment||'')}</td></tr>`}).join('')}</tbody></table></div>`}
function more(){return `<h1>Más</h1><div class="list"><div class="panel"><b>Nube</b><p class="muted">Supabase Cloud + sincronización offline. REPUESTOS IA usa registros inventory_* separados lógicamente de MANTPRO.</p><button id="sync-now" class="primary">Sincronizar ahora</button></div><div class="panel"><b>Respaldo JSON</b><p class="muted">Descarga una copia completa de REPUESTOS IA.</p><button id="backup" class="outline">Descargar respaldo</button></div><div class="panel"><b>Sesión</b><p class="muted">Usuario ${esc(C.username)}</p><button id="signout" class="danger">Cerrar sesión</button></div></div>`}
function render(){const routes={home,parts,part_new:partForm,detail,move:moveForm,capture,reports,more};$('#app').innerHTML=(routes[state.route]||home)();$('#back').hidden=['home','parts','move','reports','more'].includes(state.route);$$('#nav [data-route]').forEach(b=>b.classList.toggle('on',b.dataset.route===state.route));bind()}
function bind(){$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-part]').forEach(b=>b.onclick=()=>go('detail',{partId:b.dataset.part}));$$('[data-move-part]').forEach(b=>b.onclick=()=>go('move',{partId:b.dataset.movePart}));$('#search')?.addEventListener('input',e=>{state.filter=e.target.value;render();setTimeout(()=>{$('#search')?.focus()},0)});$('#part-form')?.addEventListener('submit',savePart);$('#move-form')?.addEventListener('submit',saveMove);$$('[data-camera]').forEach(b=>b.onclick=()=>pick('camera'));$$('[data-gallery]').forEach(b=>b.onclick=()=>pick('gallery'));$('#ocr-btn')?.addEventListener('click',analyzeCurrent);$('#capture-analyze')?.addEventListener('click',captureAnalyze);$('#excel-daily')?.addEventListener('click',exportDaily);$('#sync-now')?.addEventListener('click',sync);$('#backup')?.addEventListener('click',backup);$('#signout')?.addEventListener('click',()=>window.REPUESTOS_AUTH?.signOut())}
function savePart(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),p=add('part',d.code+' '+d.name,{...d,min:Number(d.min||0),max:Number(d.max||0),unitCost:Number(d.unitCost||0),photo:state.photo||null});if(Number(d.initial)>0)add('move','Stock inicial '+d.code,{partId:p.id,kind:'entrada',qty:Number(d.initial),ot:'INICIAL',equipment:d.equipment||'',person:C.supervisor,area:d.warehouse||'',note:'Carga inicial de inventario'});toast('Repuesto guardado');go('detail',{partId:p.id})}
function saveMove(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),p=part(d.partId);if(!p)return toast('Seleccione un repuesto');const qty=Number(d.qty||0),current=stockFor(p.id);if(['salida','ajuste-'].includes(d.kind)&&qty>current&&!confirm(`El movimiento dejará stock negativo (${current-qty}). ¿Continuar?`))return;add('move',`${d.kind} ${p.data.code}`,{...d,qty,photo:state.photo||null});toast('Movimiento registrado');go('detail',{partId:p.id})}
function pick(which){const inp=$(which==='camera'?'#camera':'#gallery');inp.value='';inp.onchange=async()=>{const f=inp.files?.[0];if(!f)return;state.photo=await compress(f);render();toast('Fotografía lista')};inp.click()}
function compress(file){return new Promise((resolve,reject)=>{const im=new Image(),u=URL.createObjectURL(file);im.onload=()=>{const max=1280,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);resolve(c.toDataURL('image/jpeg',.68))};im.onerror=reject;im.src=u})}
async function ocr(photo){if(!photo)throw Error('Primero adjunte una fotografía');if(!window.Tesseract)throw Error('OCR no disponible');const out=$('#ocr-result');if(out){out.hidden=false;out.textContent='Analizando fotografía…'}const {data}=await Tesseract.recognize(photo,'eng+spa',{logger:m=>{if(out&&m.progress)out.textContent=`Analizando ${Math.round(m.progress*100)}%…`}}),text=(data.text||'').trim(),lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean),pn=(text.match(/(?:P\/?N|PART(?:\s*NO)?|N[°º]?\s*PARTE)\s*[:#-]?\s*([A-Z0-9][A-Z0-9._\/-]{3,})/i)||[])[1]||'',code=(text.match(/(?:COD(?:IGO)?|SKU|ITEM)\s*[:#-]?\s*([A-Z0-9][A-Z0-9._\/-]{2,})/i)||[])[1]||'',name=lines.find(x=>x.length>5&&!/part|codigo|sku|item/i.test(x))||'';if(out)out.textContent=`Texto detectado: ${text.slice(0,400)||'Sin texto legible'}`;return{text,partNumber:pn,code,name}}
async function analyzeCurrent(){try{const d=await ocr(state.photo),f=$('#part-form');if(f){if(d.code&&!f.code.value)f.code.value=d.code;if(d.partNumber&&!f.partNumber.value)f.partNumber.value=d.partNumber;if(d.name&&!f.name.value)f.name.value=d.name}toast('Datos propuestos. Revise antes de guardar.')}catch(e){toast(e.message)}}
async function captureAnalyze(){try{const photo=state.photo,d=await ocr(photo);go('part_new');state.photo=photo;render();setTimeout(()=>{const f=$('#part-form');if(!f)return;f.code.value=d.code||'';f.partNumber.value=d.partNumber||'';f.name.value=d.name||''},0)}catch(e){toast(e.message)}}
function backup(){const blob=new Blob([JSON.stringify({app:'REPUESTOS IA CLOUD',version:C.version,exportedAt:iso(),records:recs()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`RESPALDO_REPUESTOS_IA_${day()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#back').onclick=()=>go(state.previous||'home');$$('#nav [data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));window.addEventListener('online',sync);window.addEventListener('repuestos-auth-ready',()=>{render();sync()});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();setTimeout(sync,1000);
})();
