/* LEVANTAMIENTO DE REPUESTOS IA CLOUD v3.1 — identificación técnica en terreno, offline-first, nube y Excel. */
(()=>{'use strict';
const C=window.REPUESTOS_CONFIG||{},STORE='repuestos-ia-records-v3',LEGACY='repuestos-ia-records-v2',CTX='repuestos-ia-context-v3',PFX=C.recordPrefix||'inventory_';
const MEDIA_DB='repuestos-ia-media-v3',MEDIA_STORE='media';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],iso=()=>new Date().toISOString(),uid=()=>crypto.randomUUID();
const state={route:'home',previous:'home',surveyId:null,editId:null,photos:[],syncing:false,filter:'',usage:'',repair:'',genesis:''};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const recs=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return[]}};
const persist=a=>localStorage.setItem(STORE,JSON.stringify(a));
const byType=t=>recs().filter(x=>x.type===t),survey=id=>byType('survey').find(x=>x.id===id),surveys=()=>byType('survey');
const context=()=>{try{return JSON.parse(localStorage.getItem(CTX)||'{}')}catch{return{}}};
const saveContext=o=>localStorage.setItem(CTX,JSON.stringify(o));
const day=(v=Date.now())=>{const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fmt=v=>v?new Date(v).toLocaleString('es-CL',{dateStyle:'short',timeStyle:'short',hour12:false}):'—';
const num=v=>Number(v)||0;
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,3200)}
function status(t,k=''){const e=$('#sync-state');if(!e)return;e.textContent=t;e.style.background=k==='ok'?'#17865b55':k==='warn'?'#b9770055':'#ffffff18'}
function make(type,title,data,id=uid()){return{id,type,title,data,at:iso(),updatedAt:iso(),dirty:true,synced:false}}
function upsert(x){const a=recs(),i=a.findIndex(y=>y.id===x.id);x.updatedAt=iso();x.dirty=true;x.synced=false;i<0?a.push(x):a[i]=x;persist(a);syncSoon();return x}
function syncSoon(){clearTimeout(syncSoon.t);syncSoon.t=setTimeout(sync,900)}
function openMedia(){return new Promise((resolve,reject)=>{const r=indexedDB.open(MEDIA_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(MEDIA_STORE))r.result.createObjectStore(MEDIA_STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function mediaPut(recordId,photos=[]){const db=await openMedia(),ids=[];await new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,'readwrite'),st=tx.objectStore(MEDIA_STORE);photos.forEach((dataUrl,i)=>{const id=`${recordId}:${i}`;ids.push(id);st.put({id,recordId,index:i,dataUrl,updatedAt:iso()})});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();return ids}
async function mediaGetMany(ids=[]){if(!ids.length)return[];const db=await openMedia(),out=[];for(const id of ids){const row=await new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,'readonly'),r=tx.objectStore(MEDIA_STORE).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});if(row?.dataUrl)out.push(row.dataUrl)}db.close();return out}
async function mediaDeleteRecord(recordId){const db=await openMedia();await new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,'readwrite'),st=tx.objectStore(MEDIA_STORE),r=st.openCursor();r.onsuccess=()=>{const c=r.result;if(!c)return;if(c.value.recordId===recordId)c.delete();c.continue()};tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
async function normalizeRemote(n){if(!n)return null;const cp=n.data?.cloudPhotos;if(Array.isArray(cp)&&cp.length){const ids=await mediaPut(n.id,cp);n={...n,data:{...n.data,photoIds:ids,photoCount:cp.length}};delete n.data.cloudPhotos}return{...n,dirty:false,synced:true}}
async function payloadForCloud(x){const p=JSON.parse(JSON.stringify({...x,dirty:false,synced:true,app:'repuestos_ia'}));if(x.type==='survey'){const photos=await mediaGetMany(x.data?.photoIds||[]);p.data={...p.data,cloudPhotos:photos}}return p}
async function sync(){if(state.syncing)return;if(!navigator.onLine){status('Offline · respaldo local activo','warn');return}if(C.requireAuth!==false&&!window.REPUESTOS_AUTH?.token()){status('Acceso pendiente','warn');return}state.syncing=true;status('Sincronizando…');try{let a=recs();for(const x of a.filter(r=>r.dirty)){const payload=await payloadForCloud(x),row={id:x.id,record_type:PFX+x.type,payload,occurred_at:x.at};const r=await fetch(`${C.supabaseUrl}/rest/v1/${C.table}?on_conflict=id`,{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)});if(!r.ok)throw Error(await r.text());x.dirty=false;x.synced=true}persist(a);const r=await fetch(`${C.supabaseUrl}/rest/v1/${C.table}?select=payload&record_type=like.${PFX}*&order=occurred_at.asc`);if(!r.ok)throw Error(await r.text());const remote=await r.json(),map=new Map(recs().map(x=>[x.id,x]));for(const row of remote){let n=row.payload;if(!n||n.app!=='repuestos_ia')continue;n=await normalizeRemote(n);const o=map.get(n.id);if(!o||(!o.dirty&&new Date(n.updatedAt||n.at)>=new Date(o.updatedAt||o.at)))map.set(n.id,n)}persist([...map.values()]);status('Nube sincronizada','ok');render()}catch(e){console.warn(e);status('Pendiente de sincronizar','warn')}finally{state.syncing=false}}
function migrate(){if(!localStorage.getItem(STORE)){try{const old=JSON.parse(localStorage.getItem(LEGACY)||'[]');persist(old)}catch{persist([])}}let changed=false,a=recs();for(const x of a){if(x.type==='survey'&&x.data?.usageClass==='Apto para uso'){x.data.usageClass='Reutilizable';x.dirty=true;x.synced=false;changed=true}if(x.type==='part'){const d=x.data||{};x.type='survey';x.title=`LEV ${d.code||''} ${d.name||''}`.trim();x.data={folio:d.folio||'',client:'',contract:'',site:'',campaign:'Migrado desde inventario v2',area:'',warehouse:d.warehouse||'',location:d.location||'',code:d.code||'',partNumber:d.partNumber||'',serialNumber:'',name:d.name||'',manufacturer:d.brand||'',quantity:num(d.initial)||1,unit:'UN',equipmentFamily:d.equipment||'',equipmentMakerModel:'',equipmentTag:'',system:'',genesis:'No determinada',genesisDetail:'Registro migrado desde REPUESTOS IA v2',physicalState:'Sin uso / almacenado',usageClass:'Pendiente de evaluación',repairability:'Pendiente de evaluación',conditionReason:'',criticality:d.criticality||'Normal',storageCondition:'No evaluada',packagingState:'No evaluado',documentation:'No evaluada',obsolete:'No determinado',disposition:'Requiere evaluación',recommendation:'Validar técnicamente',notes:'',photoIds:[],photoCount:d.photo?1:0,legacyPhoto:d.photo||null,classificationStatus:'Pendiente',createdBy:C.supervisor};x.dirty=true;x.synced=false;changed=true}}if(changed)persist(a)}
const badge=(t,k='')=>`<span class="badge ${k}">${esc(t)}</span>`,empty=t=>`<div class="empty">${esc(t)}</div>`;
const todaySurveys=()=>surveys().filter(x=>day(x.at)===day());
const classified=x=>x.data.usageClass&&!/pendiente|sin identificar/i.test(x.data.usageClass)&&x.data.repairability&&!/pendiente/i.test(x.data.repairability);
const unidentified=()=>surveys().filter(x=>!String(x.data.partNumber||'').trim()&&!String(x.data.code||'').trim());
const reusable=()=>surveys().filter(x=>/reutilizable|apto para uso/i.test(x.data.usageClass||''));
const needsReview=()=>surveys().filter(x=>!classified(x)||!x.data.equipmentFamily||/no determinada|desconocid/i.test(x.data.genesis||''));
const pending=()=>needsReview();
const grouped=(arr,key)=>{const m=new Map();for(const x of arr){const k=(x.data?.[key]||'No informado').trim()||'No informado',o=m.get(k)||{Grupo:k,Fichas:0,Cantidad:0};o.Fichas++;o.Cantidad+=num(x.data.quantity);m.set(k,o)}return [...m.values()].sort((a,b)=>b.Fichas-a.Fichas)};
function currentCampaignRecords(){const c=context();return surveys().filter(x=>(!c.client||x.data.client===c.client)&&(!c.campaign||x.data.campaign===c.campaign))}
function progressPct(){const c=context(),target=num(c.targetItems),n=currentCampaignRecords().length;return target?Math.min(100,Math.round(n/target*100)):0}
function folio(){const d=day().replaceAll('-',''),n=todaySurveys().length+1;return `LEV-${d}-${String(n).padStart(4,'0')}`}
function go(route,ctx={}){state.previous=state.route;state.route=route;Object.assign(state,ctx);render();scrollTo({top:0,behavior:'smooth'})}
function startNew(){state.editId=null;state.photos=[];go('survey_new')}
async function startEdit(id){state.editId=id;const x=survey(id);state.photos=await mediaGetMany(x?.data?.photoIds||[]);if(!state.photos.length&&x?.data?.legacyPhoto)state.photos=[x.data.legacyPhoto];go('survey_new')}
function useClass(x){const u=x.data.usageClass||'Pendiente';return /reutilizable|apto para uso/i.test(u)?'green':/no apto/i.test(u)?'red':/condicionado/i.test(u)?'yellow':''}
function surveyItem(x){const d=x.data||{};return `<button class="list-item" data-survey="${x.id}"><div class="line"><div><b>${esc(d.folio||'Sin folio')}</b> · ${esc(d.name||'Sin descripción')}</div>${badge(d.usageClass||'Pendiente',useClass(x))}</div><div class="meta">P/N ${esc(d.partNumber||'No identificado')} · ${esc(d.equipmentFamily||'Equipo no definido')} · ${esc(d.genesis||'Génesis no definida')} · Cant. ${num(d.quantity)} ${esc(d.unit||'UN')}</div></button>`}
function home(){const all=surveys(),today=todaySurveys(),c=context(),pc=progressPct(),camp=currentCampaignRecords();return `<section class="hero"><span class="eyebrow">Levantamiento técnico en terreno · ${esc(C.supervisor)}</span><h1>Levantamiento de repuestos</h1><p>Identificar lo que el cliente tiene almacenado, clasificar su condición y aplicación, asociarlo a equipos y dejar evidencia fotográfica trazable.</p></section>
<div class="context-strip"><div><small>CLIENTE / CAMPAÑA</small><b>${esc(c.client||'Configurar cliente')} · ${esc(c.campaign||'Sin campaña')}</b><span>${esc(c.site||'Faena no informada')}</span></div><button class="outline" data-go="context">Configurar</button></div>
<div class="grid stats"><div class="card stat"><small>Total levantados</small><b>${all.length}</b></div><div class="card stat"><small>Sin identificar</small><b class="${unidentified().length?'kpi-bad':''}">${unidentified().length}</b></div><div class="card stat"><small>Reutilizables</small><b class="kpi-good">${reusable().length}</b></div><div class="card stat"><small>Requieren revisión</small><b class="${needsReview().length?'kpi-bad':''}">${needsReview().length}</b></div></div>
${num(c.targetItems)?`<div class="panel"><div class="line"><b>Avance campaña</b><b>${camp.length}/${num(c.targetItems)} · ${pc}%</b></div><div class="progress"><span style="width:${pc}%"></span></div></div>`:''}
<h2>Trabajo en terreno</h2><div class="grid actions"><button class="quick" id="new-fast"><b>📷</b>Nuevo levantamiento</button><button class="quick" data-go="records"><b>▦</b>Revisar fichas</button><button class="quick" data-go="reports"><b>▤</b>Excel de avance</button><button class="quick" id="field-backup"><b>☁</b>Respaldar jornada</button></div>
<h2>Últimos levantamientos</h2><div class="list">${all.length?all.slice().sort((a,b)=>new Date(b.at)-new Date(a.at)).slice(0,8).map(surveyItem).join(''):empty('Aún no hay fichas. Use “Nuevo levantamiento” desde el teléfono.')}</div>`}
function records(){const q=state.filter.toLowerCase(),a=surveys().filter(x=>(!q||JSON.stringify(x.data).toLowerCase().includes(q))&&(!state.usage||x.data.usageClass===state.usage)&&(!state.repair||x.data.repairability===state.repair)&&(!state.genesis||x.data.genesis===state.genesis));return `<div class="line"><h1>Fichas de levantamiento</h1><button class="primary" id="new-record">Nueva</button></div><label>Buscar<input id="search" placeholder="Folio, P/N, descripción, equipo, TAG, ubicación…" value="${esc(state.filter)}"></label><div class="filtergrid"><label>Uso<select id="usage-filter"><option value="">Todos</option>${options(['Reutilizable','Uso condicionado','No apto para uso','Pendiente de evaluación'],state.usage)}</select></label><label>Reparabilidad<select id="repair-filter"><option value="">Todas</option>${options(['No requiere reparación','Reparable','No reparable','Pendiente de evaluación'],state.repair)}</select></label><label>Génesis<select id="genesis-filter"><option value="">Todas</option>${options(genesisOptions(),state.genesis)}</select></label></div><div class="list" style="margin-top:12px">${a.length?a.sort((x,y)=>new Date(y.at)-new Date(x.at)).map(surveyItem).join(''):empty('No hay fichas que coincidan con los filtros.')}</div>`}
const genesisOptions=()=>['Sobrecompra / stock excedente','Proyecto terminado','Cambio de alcance / ingeniería','Equipo dado de baja','Repuesto de contingencia','Devolución de mantenimiento','Recuperado de equipo / desarme','Obsolescencia','Compra errónea / incompatibilidad','No determinada','Otra'];
function options(arr,sel){return arr.map(v=>`<option ${v===sel?'selected':''}>${esc(v)}</option>`).join('')}
const vv=(d,k,def='')=>d?.[k]??def;
function surveyForm(){const x=state.editId?survey(state.editId):null,d=x?.data||{},c=context(),title=x?'Editar ficha':'Nuevo levantamiento',f=vv(d,'folio',folio());return `<span class="eyebrow">Ficha de levantamiento técnico</span><h1>${title}</h1><form id="survey-form">
<fieldset><legend>1. Identificación del servicio</legend><div class="formgrid"><label>Folio<input name="folio" value="${esc(f)}" required></label><label>Cliente<input name="client" value="${esc(vv(d,'client',c.client||''))}" required></label><label>Contrato / servicio<input name="contract" value="${esc(vv(d,'contract',c.contract||''))}"></label><label>Faena / planta<input name="site" value="${esc(vv(d,'site',c.site||''))}" required></label><label>Campaña / levantamiento<input name="campaign" value="${esc(vv(d,'campaign',c.campaign||''))}" required></label><label>Área<input name="area" value="${esc(vv(d,'area',''))}"></label></div></fieldset>
<fieldset><legend>2. Repuesto</legend><div class="formgrid"><label>Código / ID cliente<input name="code" value="${esc(vv(d,'code',''))}"></label><label>Número de parte (P/N)<input name="partNumber" value="${esc(vv(d,'partNumber',''))}"></label><label>Número de serie<input name="serialNumber" value="${esc(vv(d,'serialNumber',''))}"></label><label>Fabricante / marca<input name="manufacturer" value="${esc(vv(d,'manufacturer',''))}"></label></div><label>Descripción del repuesto<input name="name" value="${esc(vv(d,'name',''))}" required></label><div class="formgrid"><label>Cantidad<input name="quantity" type="number" min="0.01" step="0.01" value="${esc(vv(d,'quantity',1))}" required></label><label>Unidad<select name="unit">${options(['UN','KIT','JGO','PAR','LT','KG','M'],vv(d,'unit','UN'))}</select></label><label>Bodega / patio<input name="warehouse" value="${esc(vv(d,'warehouse',''))}"></label><label>Ubicación física<input name="location" value="${esc(vv(d,'location',''))}" placeholder="Rack, estante, nivel, sector"></label></div></fieldset>
<fieldset><legend>3. Aplicación / equipo</legend><div class="formgrid"><label>Familia / tipo de equipo<input name="equipmentFamily" value="${esc(vv(d,'equipmentFamily',''))}" placeholder="Bomba, motor, camión, grúa…"></label><label>Marca / modelo equipo<input name="equipmentMakerModel" value="${esc(vv(d,'equipmentMakerModel',''))}"></label><label>TAG / N° equipo<input name="equipmentTag" value="${esc(vv(d,'equipmentTag',''))}"></label><label>Sistema / componente<input name="system" value="${esc(vv(d,'system',''))}" placeholder="Hidráulico, transmisión, eléctrico…"></label></div></fieldset>
<fieldset><legend>4. Génesis / origen</legend><label>¿Por qué este repuesto quedó sin uso?<select name="genesis">${options(genesisOptions(),vv(d,'genesis','No determinada'))}</select></label><label>Detalle de génesis<textarea name="genesisDetail" placeholder="Antecedentes conocidos, orden de compra, proyecto, cambio de equipo…">${esc(vv(d,'genesisDetail',''))}</textarea></label></fieldset>
<fieldset><legend>5. Evaluación técnica</legend><div class="formgrid"><label>Estado físico<select name="physicalState">${options(['Nuevo sellado','Nuevo abierto / sin uso','Sin uso / almacenado','Con señales de almacenamiento prolongado','Dañado / deteriorado','Incompleto','No determinado'],vv(d,'physicalState','Sin uso / almacenado'))}</select></label><label>Clasificación de uso<select name="usageClass">${options(['Reutilizable','Uso condicionado','No apto para uso','Pendiente de evaluación'],vv(d,'usageClass','Pendiente de evaluación'))}</select></label><label>Reparabilidad<select name="repairability">${options(['No requiere reparación','Reparable','No reparable','Pendiente de evaluación'],vv(d,'repairability','Pendiente de evaluación'))}</select></label><label>Criticidad<select name="criticality">${options(['Baja','Normal','Alta','Crítica'],vv(d,'criticality','Normal'))}</select></label><label>Condición de almacenamiento<select name="storageCondition">${options(['Adecuada','Regular','Deficiente','Expuesto a intemperie','No evaluada'],vv(d,'storageCondition','No evaluada'))}</select></label><label>Embalaje / preservación<select name="packagingState">${options(['Original íntegro','Original deteriorado','Reembalado','Sin embalaje','No evaluado'],vv(d,'packagingState','No evaluado'))}</select></label><label>Documentación / trazabilidad<select name="documentation">${options(['Completa','Parcial','Sin documentación','No evaluada'],vv(d,'documentation','No evaluada'))}</select></label><label>Obsolescencia<select name="obsolete">${options(['Vigente','Obsoleto','Posible obsolescencia','No determinado'],vv(d,'obsolete','No determinado'))}</select></label></div><label>Fundamento técnico de condición<textarea name="conditionReason" placeholder="Corrosión, sello vencido, falta de componentes, preservación correcta, etc.">${esc(vv(d,'conditionReason',''))}</textarea></label></fieldset>
<fieldset><legend>6. Recomendación / disposición</legend><div class="formgrid"><label>Disposición recomendada<select name="disposition">${options(['Reutilizar / reincorporar a stock','Reservar para contingencia','Enviar a reparación','Evaluar por especialista / ingeniería','Reubicar / transferir internamente','Recuperar componentes','Dar de baja / disponer','Requiere evaluación'],vv(d,'disposition','Requiere evaluación'))}</select></label></div><label>Recomendación técnica<textarea name="recommendation" placeholder="Acción recomendada y condición para su uso">${esc(vv(d,'recommendation',''))}</textarea></label><label>Observaciones<textarea name="notes">${esc(vv(d,'notes',''))}</textarea></label></fieldset>
<fieldset><legend>7. Evidencia fotográfica</legend><p class="muted">Tome hasta 3 fotografías: vista general, etiqueta/P-N y condición o daño. Se optimizan para terreno y se respaldan en la nube.</p><div class="button-row"><button type="button" class="primary" data-camera>📷 Tomar fotografía</button><button type="button" class="outline" data-gallery>Elegir fotografía</button><button type="button" class="outline" id="ocr-btn">IA/OCR leer etiqueta</button><button type="button" class="outline" id="barcode-btn">Leer código visible</button></div><div id="photo-preview" class="photo-grid"></div><div id="ocr-result" class="callout" hidden></div></fieldset>
<button class="primary big">${x?'Guardar cambios':'Guardar ficha de levantamiento'}</button></form>`}
function detail(){const x=survey(state.surveyId);if(!x)return empty('Ficha no encontrada.');const d=x.data||{};return `<div class="line"><div><span class="eyebrow">${esc(d.folio||'FICHA')}</span><h1>${esc(d.name||'Repuesto')}</h1></div>${badge(d.usageClass||'Pendiente',useClass(x))}</div><div id="detail-photos" class="photo-grid"></div>
<div class="grid stats"><div class="card"><small>P/N</small><b>${esc(d.partNumber||'No identificado')}</b></div><div class="card"><small>Cantidad</small><b>${num(d.quantity)} ${esc(d.unit||'UN')}</b></div><div class="card"><small>Reparabilidad</small><b>${esc(d.repairability||'Pendiente')}</b></div><div class="card"><small>Génesis</small><b>${esc(d.genesis||'No determinada')}</b></div></div>
<div class="panel data-grid"><div><small>Cliente</small><b>${esc(d.client||'—')}</b></div><div><small>Faena</small><b>${esc(d.site||'—')}</b></div><div><small>Ubicación hallazgo</small><b>${esc((d.warehouse||'')+' / '+(d.location||''))}</b></div><div><small>Equipo asociado</small><b>${esc((d.equipmentFamily||'—')+' '+(d.equipmentMakerModel||''))}</b></div><div><small>TAG</small><b>${esc(d.equipmentTag||'—')}</b></div><div><small>Sistema</small><b>${esc(d.system||'—')}</b></div><div><small>Estado físico</small><b>${esc(d.physicalState||'—')}</b></div><div><small>Uso</small><b>${esc(d.usageClass||'—')}</b></div><div><small>Almacenamiento</small><b>${esc(d.storageCondition||'—')}</b></div><div><small>Disposición</small><b>${esc(d.disposition||'—')}</b></div></div>
${d.genesisDetail?`<div class="callout"><b>Antecedente / génesis:</b> ${esc(d.genesisDetail)}</div>`:''}${d.conditionReason?`<div class="callout warning"><b>Fundamento técnico:</b> ${esc(d.conditionReason)}</div>`:''}${d.recommendation?`<div class="callout"><b>Recomendación:</b> ${esc(d.recommendation)}</div>`:''}
<div class="button-row"><button id="edit-survey" class="primary">Editar ficha</button><button id="duplicate-survey" class="outline">Duplicar para similar</button></div>`}
function contextForm(){const c=context();return `<span class="eyebrow">Campaña de levantamiento</span><h1>Cliente y servicio</h1><form id="context-form"><div class="formgrid"><label>Cliente<input name="client" required value="${esc(c.client||'')}"></label><label>Contrato / servicio<input name="contract" value="${esc(c.contract||'')}"></label><label>Faena / planta<input name="site" required value="${esc(c.site||'')}"></label><label>Campaña<input name="campaign" required value="${esc(c.campaign||'')}"></label><label>Levantador / responsable<input name="inspector" value="${esc(c.inspector||C.supervisor)}"></label><label>Meta de repuestos (opcional)<input name="targetItems" type="number" min="0" value="${num(c.targetItems)||''}"></label></div><button class="primary">Guardar campaña</button></form>`}
function safe(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9_-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,60)||'SIN_DATO'}
function detailRow(x){const d=x.data||{};return{FechaHora:fmt(x.at),Folio:d.folio||'',Cliente:d.client||'',Contrato:d.contract||'',Faena:d.site||'',Campaña:d.campaign||'',Area:d.area||'',Codigo:d.code||'',NumeroParte:d.partNumber||'',Serie:d.serialNumber||'',Descripcion:d.name||'',Fabricante:d.manufacturer||'',Cantidad:num(d.quantity),Unidad:d.unit||'',Bodega:d.warehouse||'',Ubicacion:d.location||'',FamiliaEquipo:d.equipmentFamily||'',MarcaModeloEquipo:d.equipmentMakerModel||'',TAGEquipo:d.equipmentTag||'',Sistema:d.system||'',Genesis:d.genesis||'',DetalleGenesis:d.genesisDetail||'',EstadoFisico:d.physicalState||'',ClasificacionUso:d.usageClass||'',Reparabilidad:d.repairability||'',Criticidad:d.criticality||'',Almacenamiento:d.storageCondition||'',Embalaje:d.packagingState||'',Documentacion:d.documentation||'',Obsolescencia:d.obsolete||'',FundamentoTecnico:d.conditionReason||'',Disposicion:d.disposition||'',Recomendacion:d.recommendation||'',Fotos:num(d.photoCount),Observaciones:d.notes||'',Levantador:d.createdBy||''}}
function makeWorkbook(dateOnly=false){if(!window.XLSX)throw Error('Excel no disponible');const c=context(),base=dateOnly?todaySurveys():surveys(),wb=XLSX.utils.book_new(),camp=currentCampaignRecords(),target=num(c.targetItems),today=todaySurveys();const sum=[{Indicador:'Fecha de reporte',Valor:day()},{Indicador:'Cliente',Valor:c.client||''},{Indicador:'Faena / planta',Valor:c.site||''},{Indicador:'Campaña',Valor:c.campaign||''},{Indicador:'Meta campaña',Valor:target||''},{Indicador:'Fichas campaña acumuladas',Valor:camp.length},{Indicador:'Avance campaña %',Valor:target?Math.round(camp.length/target*100):''},{Indicador:'Fichas levantadas hoy',Valor:today.length},{Indicador:'Cantidad física levantada hoy',Valor:today.reduce((n,x)=>n+num(x.data.quantity),0)},{Indicador:'Fotografías hoy',Valor:today.reduce((n,x)=>n+num(x.data.photoCount),0)},{Indicador:'Clasificadas hoy',Valor:today.filter(classified).length},{Indicador:'Pendientes validación acumulados',Valor:pending().length},{Indicador:'Reutilizables hoy',Valor:today.filter(x=>/reutilizable|apto para uso/i.test(x.data.usageClass||'')).length},{Indicador:'Uso condicionado hoy',Valor:today.filter(x=>x.data.usageClass==='Uso condicionado').length},{Indicador:'No aptos hoy',Valor:today.filter(x=>x.data.usageClass==='No apto para uso').length},{Indicador:'Reparables hoy',Valor:today.filter(x=>x.data.repairability==='Reparable').length}];appendSheet(wb,sum,'RESUMEN AVANCE');appendSheet(wb,base.map(detailRow),dateOnly?'LEVANTAMIENTO HOY':'MAESTRO ACUMULADO');appendSheet(wb,grouped(base,'equipmentFamily'),'POR EQUIPO');appendSheet(wb,grouped(base,'genesis'),'POR GENESIS');appendSheet(wb,grouped(base,'usageClass'),'POR USO');appendSheet(wb,grouped(base,'repairability'),'POR REPARABILIDAD');appendSheet(wb,grouped(base,'disposition'),'POR DISPOSICION');appendSheet(wb,pending().map(detailRow),'PENDIENTES');return wb}
function appendSheet(wb,rows,name){const ws=XLSX.utils.json_to_sheet(rows.length?rows:[{SinDatos:'Sin registros'}]);ws['!cols']=Object.keys(rows[0]||{SinDatos:''}).map(k=>({wch:Math.min(38,Math.max(12,k.length+2))}));XLSX.utils.book_append_sheet(wb,ws,name.slice(0,31))}
function exportDaily(){try{const wb=makeWorkbook(true);XLSX.writeFile(wb,`AVANCE_DIARIO_LEVANTAMIENTO_${safe(context().client||'CLIENTE')}_${day()}.xlsx`);toast('Excel diario generado')}catch(e){toast(e.message)}}
function exportMaster(){try{const wb=makeWorkbook(false);XLSX.writeFile(wb,`MAESTRO_LEVANTAMIENTO_${safe(context().client||'CLIENTE')}_${day()}.xlsx`);toast('Excel acumulado generado')}catch(e){toast(e.message)}}
async function backupData(){const out=[];for(const x of recs()){const y=JSON.parse(JSON.stringify(x));if(x.type==='survey')y.data.cloudPhotos=await mediaGetMany(x.data?.photoIds||[]);out.push(y)}return{app:'LEVANTAMIENTO DE REPUESTOS IA CLOUD',version:C.version,exportedAt:iso(),context:context(),records:out}}
async function fieldBackup(){if(!window.JSZip||!window.XLSX)return toast('Módulo de respaldo no disponible');toast('Preparando respaldo de jornada…');try{const zip=new JSZip(),data=await backupData(),wb=makeWorkbook(true),xlsx=XLSX.write(wb,{bookType:'xlsx',type:'array'}),base=`RESPALDO_${safe(context().client||'CLIENTE')}_${day()}`;zip.file(`${base}.xlsx`,xlsx);zip.file(`${base}.json`,JSON.stringify(data,null,2));for(const x of todaySurveys()){const photos=await mediaGetMany(x.data?.photoIds||[]);photos.forEach((u,i)=>{const b64=u.split(',')[1];if(b64)zip.file(`FOTOS/${safe(x.data.folio||x.id)}_${i+1}.jpg`,b64,{base64:true})})}const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}}),file=new File([blob],`${base}.zip`,{type:'application/zip'});if(navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({files:[file],title:'Respaldo levantamiento',text:`Respaldo ${context().client||''} ${day()}`})}else downloadBlob(file,file.name);toast('Respaldo de jornada generado')}catch(e){if(e?.name!=='AbortError')toast('No fue posible respaldar: '+e.message)}}
async function backupJSON(){const data=await backupData(),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});downloadBlob(blob,`RESPALDO_COMPLETO_REPUESTOS_IA_${day()}.json`);toast('Respaldo completo descargado')}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function reports(){const t=todaySurveys(),all=surveys();return `<h1>Centro de reportes</h1><div class="grid stats"><div class="card stat"><small>Fichas hoy</small><b>${t.length}</b></div><div class="card stat"><small>Fotos hoy</small><b>${t.reduce((n,x)=>n+num(x.data.photoCount),0)}</b></div><div class="card stat"><small>Reutilizables hoy</small><b>${t.filter(x=>/reutilizable|apto para uso/i.test(x.data.usageClass||'')).length}</b></div><div class="card stat"><small>Sin identificar hoy</small><b>${t.filter(x=>!String(x.data.partNumber||'').trim()&&!String(x.data.code||'').trim()).length}</b></div></div>
<div class="grid report-actions"><div class="panel"><h2>Avance diario Excel</h2><p>Resumen de avance + levantamiento del día + clasificación por equipo, génesis, uso, reparabilidad y pendientes.</p><button id="excel-daily" class="primary">Descargar Excel diario</button></div><div class="panel"><h2>Maestro acumulado</h2><p>Base completa para entrega al cliente, con trazabilidad y clasificación técnica.</p><button id="excel-master" class="primary">Descargar Excel acumulado</button></div><div class="panel"><h2>Respaldo de jornada</h2><p>ZIP con Excel, JSON y fotografías tomadas hoy. Ideal para guardar o compartir desde el teléfono.</p><button id="field-backup2" class="primary">Generar / compartir ZIP</button></div></div>
<h2>Distribución acumulada</h2><div class="grid summary-groups"><div class="panel"><b>Por uso</b>${miniGroup(grouped(all,'usageClass'))}</div><div class="panel"><b>Por génesis</b>${miniGroup(grouped(all,'genesis').slice(0,8))}</div><div class="panel"><b>Por equipo</b>${miniGroup(grouped(all,'equipmentFamily').slice(0,8))}</div></div>`}
function miniGroup(a){return `<div class="mini-group">${a.map(x=>`<div><span>${esc(x.Grupo)}</span><b>${x.Fichas}</b></div>`).join('')||'<p class="muted">Sin datos</p>'}</div>`}
function more(){return `<h1>Más</h1><div class="list"><div class="panel"><b>Sincronización cloud</b><p class="muted">Los registros se conservan localmente sin señal y se sincronizan con Supabase al recuperar Internet.</p><button id="sync-now" class="primary">Sincronizar ahora</button></div><div class="panel"><b>Respaldo completo</b><p class="muted">Exporta todas las fichas y fotografías en JSON para recuperación técnica.</p><button id="backup-json" class="outline">Descargar respaldo completo</button></div><div class="panel"><b>Cliente y campaña</b><p class="muted">Configure los datos que se precargan en cada ficha.</p><button class="outline" data-go="context">Configurar campaña</button></div><div class="panel"><b>Sesión</b><p class="muted">Usuario ${esc(C.username)}</p><button id="signout" class="danger">Cerrar sesión</button></div></div>`}
function render(){const routes={home,records,survey_new:surveyForm,detail,reports,more,context:contextForm};$('#app').innerHTML=(routes[state.route]||home)();$('#back').hidden=['home','records','reports','more'].includes(state.route);$$('#nav [data-route]').forEach(b=>b.classList.toggle('on',b.dataset.route===state.route));bind();if(state.route==='survey_new')drawPhotoPreview();if(state.route==='detail')loadDetailPhotos()}
function bind(){$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-survey]').forEach(b=>b.onclick=()=>go('detail',{surveyId:b.dataset.survey}));$('#new-fast')?.addEventListener('click',startNew);$('#new-record')?.addEventListener('click',startNew);$('#survey-form')?.addEventListener('submit',saveSurvey);$('#context-form')?.addEventListener('submit',saveCtx);$('#search')?.addEventListener('input',e=>{state.filter=e.target.value;render();setTimeout(()=>{$('#search')?.focus()},0)});$('#usage-filter')?.addEventListener('change',e=>{state.usage=e.target.value;render()});$('#repair-filter')?.addEventListener('change',e=>{state.repair=e.target.value;render()});$('#genesis-filter')?.addEventListener('change',e=>{state.genesis=e.target.value;render()});$$('[data-camera]').forEach(b=>b.onclick=()=>pick('camera'));$$('[data-gallery]').forEach(b=>b.onclick=()=>pick('gallery'));$('#ocr-btn')?.addEventListener('click',analyzeCurrent);$('#barcode-btn')?.addEventListener('click',scanBarcode);$('#edit-survey')?.addEventListener('click',()=>startEdit(state.surveyId));$('#duplicate-survey')?.addEventListener('click',duplicateSurvey);$('#excel-daily')?.addEventListener('click',exportDaily);$('#excel-master')?.addEventListener('click',exportMaster);$('#field-backup')?.addEventListener('click',fieldBackup);$('#field-backup2')?.addEventListener('click',fieldBackup);$('#sync-now')?.addEventListener('click',sync);$('#backup-json')?.addEventListener('click',backupJSON);$('#signout')?.addEventListener('click',()=>window.REPUESTOS_AUTH?.signOut())}
async function saveSurvey(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),ctx=context(),existing=state.editId?survey(state.editId):null,id=existing?.id||uid();d.quantity=num(d.quantity);d.photoCount=state.photos.length;d.createdBy=existing?.data?.createdBy||ctx.inspector||C.supervisor;d.classificationStatus=(d.usageClass==='Pendiente de evaluación'||d.repairability==='Pendiente de evaluación')?'Pendiente':'Clasificado';if(existing)await mediaDeleteRecord(id);d.photoIds=await mediaPut(id,state.photos);const x=existing?{...existing,title:`${d.folio} ${d.name}`,data:d}:make('survey',`${d.folio} ${d.name}`,d,id);upsert(x);state.editId=null;state.photos=[];toast('Ficha guardada y respaldada localmente');go('detail',{surveyId:id})}
function saveCtx(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.targetItems=num(d.targetItems);saveContext(d);toast('Cliente y campaña configurados');go('home')}
async function duplicateSurvey(){const x=survey(state.surveyId);if(!x)return;state.editId=null;state.photos=await mediaGetMany(x.data?.photoIds||[]);const copy=JSON.parse(JSON.stringify(x.data));copy.folio=folio();copy.serialNumber='';copy.code='';copy.partNumber='';copy.name='';copy.photoIds=[];copy.photoCount=state.photos.length;state.prefill=copy;go('survey_new');setTimeout(()=>prefillForm(copy),0)}
function prefillForm(d){const f=$('#survey-form');if(!f)return;for(const [k,v] of Object.entries(d)){if(f.elements[k]&&typeof v!=='object')f.elements[k].value=v}drawPhotoPreview()}
function pick(which){if(state.photos.length>=3)return toast('Máximo 3 fotografías por ficha');const inp=$(which==='camera'?'#camera':'#gallery');inp.value='';inp.onchange=async()=>{const f=inp.files?.[0];if(!f)return;state.photos.push(await compress(f));drawPhotoPreview();toast(`Fotografía ${state.photos.length}/3 lista`)};inp.click()}
function drawPhotoPreview(){const e=$('#photo-preview');if(!e)return;e.innerHTML=state.photos.map((p,i)=>`<div class="photo-card"><img class="photo" src="${p}"><button type="button" class="photo-remove" data-rm-photo="${i}">×</button><small>${i===0?'Vista general':i===1?'Etiqueta / P-N':'Condición / detalle'}</small></div>`).join('')||'<div class="empty compact">Sin fotografías aún.</div>';$$('[data-rm-photo]').forEach(b=>b.onclick=()=>{state.photos.splice(Number(b.dataset.rmPhoto),1);drawPhotoPreview()})}
async function loadDetailPhotos(){const x=survey(state.surveyId),e=$('#detail-photos');if(!x||!e)return;let photos=await mediaGetMany(x.data?.photoIds||[]);if(!photos.length&&x.data?.legacyPhoto)photos=[x.data.legacyPhoto];e.innerHTML=photos.map((p,i)=>`<div class="photo-card"><img class="photo" src="${p}"><small>Evidencia ${i+1}</small></div>`).join('')||'<div class="empty compact">Sin evidencia fotográfica.</div>'}
function compress(file){return new Promise((resolve,reject)=>{const im=new Image(),u=URL.createObjectURL(file);im.onload=()=>{const max=900,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);resolve(c.toDataURL('image/jpeg',.55))};im.onerror=reject;im.src=u})}
async function ocr(photo){if(!photo)throw Error('Primero tome una fotografía');if(!window.Tesseract)throw Error('OCR no disponible');const out=$('#ocr-result');if(out){out.hidden=false;out.textContent='Analizando fotografía…'}const {data}=await Tesseract.recognize(photo,'eng+spa',{logger:m=>{if(out&&m.progress)out.textContent=`Analizando ${Math.round(m.progress*100)}%…`}}),text=(data.text||'').trim(),lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean),pn=(text.match(/(?:P\/?N|PART(?:\s*(?:NO|NUMBER))?|N[°º]?\s*PARTE)\s*[:#-]?\s*([A-Z0-9][A-Z0-9._\/-]{3,})/i)||[])[1]||'',sn=(text.match(/(?:S\/?N|SERIAL(?:\s*(?:NO|NUMBER))?)\s*[:#-]?\s*([A-Z0-9][A-Z0-9._\/-]{3,})/i)||[])[1]||'',code=(text.match(/(?:COD(?:IGO)?|SKU|ITEM)\s*[:#-]?\s*([A-Z0-9][A-Z0-9._\/-]{2,})/i)||[])[1]||'',name=lines.find(x=>x.length>5&&!/part|codigo|serial|sku|item/i.test(x))||'';if(out)out.textContent=`Texto detectado: ${text.slice(0,500)||'Sin texto legible'}`;return{text,partNumber:pn,serialNumber:sn,code,name}}
async function analyzeCurrent(){try{const d=await ocr(state.photos[1]||state.photos[0]),f=$('#survey-form');if(f){if(d.code&&!f.code.value)f.code.value=d.code;if(d.partNumber&&!f.partNumber.value)f.partNumber.value=d.partNumber;if(d.serialNumber&&!f.serialNumber.value)f.serialNumber.value=d.serialNumber;if(d.name&&!f.name.value)f.name.value=d.name}toast('IA/OCR propuso datos. Revise antes de guardar.')}catch(e){toast(e.message)}}
async function scanBarcode(){if(!state.photos.length)return toast('Primero tome foto de la etiqueta');if(!('BarcodeDetector'in window))return toast('Este teléfono/navegador no soporta lectura automática de código. Use IA/OCR.');try{const detector=new BarcodeDetector({formats:['code_128','code_39','ean_13','ean_8','qr_code','data_matrix']}),img=new Image();img.src=state.photos[1]||state.photos[0];await img.decode();const codes=await detector.detect(img);if(!codes.length)return toast('No se detectó código');const f=$('#survey-form'),v=codes[0].rawValue||'';if(f&&!f.partNumber.value)f.partNumber.value=v;toast('Código detectado: '+v)}catch(e){toast('No fue posible leer código: '+e.message)}}
$('#back').onclick=()=>go(state.previous||'home');$$('#nav [data-route]').forEach(b=>b.onclick=()=>{if(b.dataset.route==='survey_new')startNew();else go(b.dataset.route)});window.addEventListener('online',sync);window.addEventListener('repuestos-auth-ready',()=>{render();sync()});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});migrate();render();setTimeout(sync,1000);
})();
