/* REPUESTOS IA CLOUD 2.0 — autenticación Supabase compatible con MANTPRO IA Cloud */
(()=>{'use strict';
 const C=window.REPUESTOS_CONFIG||{},base=(C.supabaseUrl||'').replace(/\/$/,''),KEY='repuestos-cloud-session-v2';
 const rawFetch=window.fetch.bind(window);const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};const write=s=>s?localStorage.setItem(KEY,JSON.stringify(s)):localStorage.removeItem(KEY);const token=()=>read()?.access_token||'';
 async function refresh(){const s=read();if(!s?.refresh_token)return false;try{const r=await rawFetch(base+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:C.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})});if(!r.ok)throw Error();const n=await r.json();write({...n,expires_at:Date.now()+(Number(n.expires_in)||3600)*1000});return true}catch{write(null);return false}}
 async function ensure(){const s=read();if(!s)return false;if((s.expires_at||0)-Date.now()<120000)return refresh();return true}
 window.fetch=async(url,options={})=>{if(typeof url==='string'&&base&&url.startsWith(base)){await ensure();const h=new Headers(options.headers||{});h.set('apikey',C.supabaseAnonKey||'');if(token())h.set('Authorization','Bearer '+token());return rawFetch(url,{...options,headers:h})}return rawFetch(url,options)};
 function overlay(){if(document.getElementById('auth-overlay'))return;const box=document.createElement('div');box.id='auth-overlay';box.className='auth-overlay';box.innerHTML=`<form id="auth-form" class="auth-card"><span class="eyebrow">Acceso privado · Nube</span><h1>REPUESTOS IA</h1><p>Usa el mismo acceso de MANTPRO IA Cloud.</p><label>Usuario<input required autocomplete="username" name="username" value="${C.username||'esteban'}"></label><label>Contraseña<input required minlength="8" autocomplete="current-password" type="password" name="password"></label><p id="auth-message" class="muted">La sesión quedará guardada en este dispositivo.</p><button class="primary">Ingresar</button><button type="button" id="auth-register" class="outline">Crear usuario por primera vez</button></form>`;document.body.appendChild(box);box.querySelector('#auth-form').onsubmit=login;box.querySelector('#auth-register').onclick=register}
 function credentials(f){const d=new FormData(f);return{username:String(d.get('username')||'').trim().toLowerCase(),password:String(d.get('password')||'')}}
 function accept(data){write({...data,expires_at:Date.now()+(Number(data.expires_in)||3600)*1000});document.getElementById('auth-overlay')?.remove();window.dispatchEvent(new Event('repuestos-auth-ready'))}
 async function login(e){e.preventDefault();const f=e.currentTarget,{username,password}=credentials(f),msg=document.getElementById('auth-message');if(username!==(C.username||'esteban').toLowerCase()){msg.textContent='Usuario incorrecto.';msg.className='error';return}msg.textContent='Verificando…';try{const r=await rawFetch(base+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:C.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({email:C.allowedEmail,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.msg||d.message||'Acceso rechazado');accept(d)}catch(err){msg.textContent='No fue posible ingresar: '+err.message;msg.className='error'}}
 async function register(){const f=document.getElementById('auth-form'),{username,password}=credentials(f),msg=document.getElementById('auth-message');if(username!==(C.username||'esteban').toLowerCase()||password.length<8){msg.textContent='Usuario esteban y contraseña de al menos 8 caracteres.';msg.className='error';return}try{const r=await rawFetch(base+'/auth/v1/signup',{method:'POST',headers:{apikey:C.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({email:C.allowedEmail,password,data:{name:C.supervisor,username:C.username,app:'repuestos'}})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.msg||d.message||'No se pudo crear');if(d.access_token)accept(d);else{msg.textContent='Usuario creado. Ahora pulsa Ingresar.';msg.className='ok'}}catch(err){msg.textContent=/already registered/i.test(err.message)?'El usuario ya existe. Pulsa Ingresar.':'Error: '+err.message;msg.className='error'}}
 async function start(){if(location.hostname==='localhost'||location.hostname==='127.0.0.1'){window.dispatchEvent(new Event('repuestos-auth-ready'));return}if(C.requireAuth===false){window.dispatchEvent(new Event('repuestos-auth-ready'));return}if(await ensure()){window.dispatchEvent(new Event('repuestos-auth-ready'))}else overlay()}
 window.REPUESTOS_AUTH={token,ensure,signOut:()=>{write(null);location.reload()}};start();setInterval(ensure,60000);
})();
