/* MANTPRO IA Cloud 3.1 — operación móvil/PC, offline-first y sincronización Supabase. */
(()=>{
  'use strict';
  const C=window.MANTPRO_CONFIG||{}, STORE='mantpro-records-v3', LEGACY='mantpro-records';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], iso=()=>new Date().toISOString(), uid=()=>crypto.randomUUID();
  const state={route:'home',previous:'home',jobId:null,walkId:null,photo:null,installPrompt:null,syncing:false};
  const monthNames=['01_Enero','02_Febrero','03_Marzo','04_Abril','05_Mayo','06_Junio','07_Julio','08_Agosto','09_Septiembre','10_Octubre','11_Noviembre','12_Diciembre'];
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
  function records(){try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return[]}}
  function persist(a){localStorage.setItem(STORE,JSON.stringify(a))}
  function migrate(){if(localStorage.getItem(STORE))return;try{const a=JSON.parse(localStorage.getItem(LEGACY)||'[]');persist(a.map(x=>({...x,dirty:!x.synced,updatedAt:x.updatedAt||x.at||iso()})))}catch{persist([])}}
  function find(id){return records().find(x=>x.id===id)}
  function upsert(x){const a=records(),i=a.findIndex(y=>y.id===x.id);x.updatedAt=iso();x.dirty=true;x.synced=false;if(i<0)a.push(x);else a[i]=x;persist(a);syncSoon();return x}
  function add(type,title,data={}){const x={id:uid(),type,title,data,at:iso(),updatedAt:iso(),dirty:true,synced:false};return upsert(x)}
  function list(type){return records().filter(x=>!type||x.type===type)}
  function fmt(v){if(!v)return'No registrado';const d=new Date(v);return Number.isNaN(d.valueOf())?'No registrado':d.toLocaleString('es-CL',{dateStyle:'short',timeStyle:'short',hour12:false})}
  function time(v){if(!v)return'—';return new Date(v).toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit',hour12:false})}
  function dateKey(v){const d=new Date(v||Date.now());return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
  function duration(start,end){if(!start||!end)return'No registrado';const ms=Math.max(0,new Date(end)-new Date(start)),h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);return `${h} h ${String(m).padStart(2,'0')} min`}
  function durationMs(ms){ms=Math.max(0,Number(ms)||0);const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);return `${h} h ${String(m).padStart(2,'0')} min`}
  function pauseMs(job){return (job.data.pauses||[]).reduce((n,p)=>n+(p.end?new Date(p.end)-new Date(p.start):0),0)}
  function netDuration(job){if(!job.data.actualStart||!job.data.actualEnd)return'No registrado';const ms=Math.max(0,new Date(job.data.actualEnd)-new Date(job.data.actualStart)-pauseMs(job)),h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);return `${h} h ${String(m).padStart(2,'0')} min`}
  function status(text,kind=''){const e=$('#state');if(!e)return;e.textContent=text;e.className='sync-state '+kind}
  function toast(text){const e=$('#toast');e.textContent=text;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,3200)}
  function titleFor(x){return x.title||x.data?.folio||x.data?.equip||'Registro'}
  function badge(text,kind=''){return `<span class="badge ${kind}">${esc(text)}</span>`}
  function empty(text){return `<div class="empty">${esc(text)}</div>`}
  function activeJobs(){return list('job').filter(x=>!x.data.actualEnd)}
  function linked(type,jobId){return list(type).filter(x=>x.data?.jobId===jobId)}
  function jobStatus(j){if(j.data.actualEnd)return'Terminado';if(j.data.pauseStartAt)return'Pausado';if(j.data.actualStart)return'En ejecución';if(j.data.lotoStart)return'En bloqueo';if(j.data.docsStart)return'Documentación';return'Programado'}
  function riskClass(r){return /alto|crítico/i.test(r||'')?'red':/medio/i.test(r||'')?'yellow':'green'}
  function folio(){const d=new Date(),a=list('job').filter(x=>new Date(x.at).getFullYear()===d.getFullYear()).length+1;return `OT-${d.getFullYear()}-${String(a).padStart(5,'0')}`}
  function syncSoon(){clearTimeout(syncSoon.t);syncSoon.t=setTimeout(sync,700)}
  async function sync(){
    if(state.syncing)return;if(!navigator.onLine){status('Sin señal · guardado local','warn');return}
    if(!window.MANTPRO_AUTH?.token()){status('Vinculación pendiente','warn');return}
    state.syncing=true;status('Sincronizando…');
    try{
      let local=records();
      for(const x of local.filter(r=>r.dirty)){
        const r=await fetch(C.supabaseUrl+'/rest/v1/mantpro_records?on_conflict=id',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:x.id,record_type:x.type,payload:{...x,dirty:false,synced:true},occurred_at:x.at})});
        if(!r.ok)throw Error((await r.text())||`Error ${r.status}`);x.dirty=false;x.synced=true;
      }
      persist(local);
      const r=await fetch(C.supabaseUrl+'/rest/v1/mantpro_records?select=payload&order=occurred_at.asc');if(!r.ok)throw Error((await r.text())||`Error ${r.status}`);
      const remote=await r.json(),map=new Map(records().map(x=>[x.id,x]));
      remote.forEach(row=>{const n=row.payload,o=map.get(n?.id);if(!n)return;if(!o||(!o.dirty&&new Date(n.updatedAt||n.at)>=new Date(o.updatedAt||o.at)))map.set(n.id,{...n,dirty:false,synced:true})});
      persist([...map.values()]);status('Sincronizado','ok');if(!document.querySelector('input,textarea,select:focus'))render();
    }catch(err){console.warn(err);status('Pendiente de sincronizar','warn')}
    finally{state.syncing=false}
  }
  function go(route,ctx={}){state.previous=state.route;state.route=route;Object.assign(state,ctx);state.photo=null;render();scrollTo({top:0,behavior:'smooth'})}
  function top(){const detail=!['home','jobs','safety','reports','more'].includes(state.route);$('#back').hidden=!detail;$('#nav').classList.toggle('hide',detail);$$('#nav [data-route]').forEach(b=>b.classList.toggle('on',b.dataset.route===state.route))}
  function home(){
    const all=records(),today=dateKey(),jobs=list('job'),safety=list('safety'),todayJobs=jobs.filter(x=>dateKey(x.data.actualStart||x.at)===today),openSafety=safety.filter(x=>!x.data.closedAt);
    return `<section class="hero"><span class="eyebrow">Supervisor · ${esc(C.supervisor)}</span><h1>Registro en terreno</h1><p>Los datos del teléfono y computador se guardan en la misma nube.</p></section>
    <div class="grid stats"><div class="card stat"><div class="label">OT de hoy</div><div class="num">${todayJobs.length}</div></div><div class="card stat"><div class="label">En ejecución</div><div class="num">${activeJobs().length}</div></div><div class="card stat"><div class="label">Desviaciones abiertas</div><div class="num">${openSafety.length}</div></div><div class="card stat"><div class="label">Pendientes nube</div><div class="num">${all.filter(x=>x.dirty).length}</div></div></div>
    <h2>Acciones rápidas</h2><div class="grid actions"><button class="quick" data-go="job_new"><b>▣</b>Nueva orden</button><button class="quick" data-go="progress_new"><b>＋</b>Registrar avance</button><button class="quick" data-go="safety_new"><b>⚠</b>Desviación</button><button class="quick" data-go="walk_new"><b>◉</b>Caminata</button></div>
    <h2>Trabajos activos</h2><div class="list">${activeJobs().length?activeJobs().slice().reverse().map(jobItem).join(''):empty('No hay trabajos activos.')}</div>`
  }
  function jobItem(j){const p=Number(j.data.progress||0),s=jobStatus(j);return `<button class="list-item" data-open-job="${j.id}"><div class="line"><div><b>${esc(j.data.folio||'OT')}</b> · ${esc(j.data.equip)}</div>${badge(s,s==='Terminado'?'green':s==='Pausado'?'yellow':'blue')}</div><div class="meta">${esc(j.data.task||'')} · ${esc(j.data.plant||'Planta no informada')}</div><div class="progress"><span style="width:${Math.max(0,Math.min(100,p))}%"></span></div><small>${p}% de avance</small></button>`}
  function jobs(){const a=list('job').slice().sort((x,y)=>new Date(y.at)-new Date(x.at));return `<div class="button-row"><h1 style="flex:1">Órdenes de trabajo</h1><button class="primary" data-go="job_new">Nueva OT</button></div><div class="list">${a.length?a.map(jobItem).join(''):empty('Aún no hay órdenes de trabajo.')}</div>`}
  function jobForm(){const tech=list('technician');return `<span class="eyebrow">Nueva orden</span><h1>Trabajo de mantención</h1><form id="record-form" data-form="job"><label>Folio<input name="folio" value="${folio()}" required></label><div class="grid"><label>Planta<input name="plant" required placeholder="Ej: Planta La Negra"></label><label>Área<input name="area" required placeholder="Ej: Bombas"></label></div><label>Equipo / TAG<input name="equip" required placeholder="Ej: Bomba P-101"></label><label>Trabajo requerido<textarea name="task" required placeholder="Describe el alcance del trabajo"></textarea></label><div class="grid"><label>Tipo<select name="maintenance"><option>Preventiva</option><option>Correctiva</option><option>Predictiva</option><option>Inspección</option><option>Emergencia</option></select></label><label>Prioridad<select name="priority"><option>Normal</option><option>Alta</option><option>Crítica</option></select></label></div><div class="grid"><label>Inicio programado<input name="plannedStart" type="datetime-local"></label><label>Término programado<input name="plannedEnd" type="datetime-local"></label></div><label>Técnicos asignados<input name="technicians" list="tech-list" placeholder="Nombres separados por coma"><datalist id="tech-list">${tech.map(t=>`<option value="${esc(t.data.name)}">`).join('')}</datalist></label><button type="button" class="outline" data-photo>📷 Adjuntar fotografía inicial</button><div id="photo-preview"></div><button class="primary">Guardar orden de trabajo</button></form>`}
  function timerCard(label,value,action,button,disabled=false){return `<div class="timer"><strong>${esc(label)}</strong><time>${fmt(value)}</time>${action?`<button data-action="${action}" ${disabled?'disabled':''}>${esc(button)}</button>`:''}</div>`}
  function jobDetail(){
    const j=find(state.jobId);if(!j)return empty('La orden no está disponible.');const d=j.data,prog=linked('progress',j.id),saf=linked('safety',j.id),kpi=linked('kpi',j.id),open=saf.filter(x=>!x.data.closedAt),paused=!!d.pauseStartAt;
    return `<div class="line"><div><span class="eyebrow">${esc(d.folio)}</span><h1>${esc(d.equip)}</h1></div>${badge(jobStatus(j),d.actualEnd?'green':paused?'yellow':'blue')}</div><div class="hero"><h3>${esc(d.task)}</h3><p>${esc(d.plant)} · ${esc(d.area)} · ${esc(d.maintenance)}</p><div class="progress"><span style="width:${Number(d.progress||0)}%"></span></div><b>${Number(d.progress||0)}% de avance</b></div>
    <h2>Tiempos reales del trabajo</h2><div class="callout"><b>Importante:</b> estas horas corresponden a la ejecución en terreno. La fecha de emisión del informe se registra aparte.</div><div class="timer-grid section">
      ${timerCard('Inicio documentación seguridad',d.docsStart,'docs-start','Iniciar documentación',!!d.docsStart)}${timerCard('Término documentación',d.docsEnd,'docs-end','Terminar documentación',!d.docsStart||!!d.docsEnd)}
      ${timerCard('Inicio bloqueo / aislamiento',d.lotoStart,'loto-start','Iniciar bloqueo',!!d.lotoStart)}${timerCard('Energía cero verificada',d.zeroVerifiedAt,'zero','Confirmar energía cero',!d.lotoStart||!!d.zeroVerifiedAt)}${timerCard('Término bloqueo / normalización',d.lotoEnd,'loto-end','Registrar término',!d.lotoStart||!!d.lotoEnd)}
      ${timerCard('Inicio real de ejecución',d.actualStart,'work-start','Iniciar trabajo',!d.zeroVerifiedAt||!!d.actualStart)}${timerCard('Término real de ejecución',d.actualEnd,'work-end','Finalizar trabajo',!d.actualStart||!!d.actualEnd)}<div class="timer"><strong>Pausas acumuladas</strong><time>${durationMs(pauseMs(j))}${paused?' · pausa activa':''}</time><button data-action="${paused?'resume':'pause'}" ${!d.actualStart||!!d.actualEnd?'disabled':''}>${paused?'Reanudar':'Pausar'}</button></div>
    </div><div class="grid stats"><div class="card"><small>Documentación</small><b>${duration(d.docsStart,d.docsEnd)}</b></div><div class="card"><small>Bloqueo / LOTO</small><b>${duration(d.lotoStart,d.lotoEnd)}</b></div><div class="card"><small>Ejecución neta</small><b>${netDuration(j)}</b></div><div class="card"><small>Técnicos</small><b>${esc(d.technicians||'No informados')}</b></div></div>
    <h2>Registro del trabajo</h2><div class="button-row no-print"><button data-job-go="progress_new">＋ Avance</button><button data-job-go="safety_new">⚠ Desviación</button><button data-job-go="kpi_new">★ Evaluar técnico</button><button data-job-go="job_report" class="primary">▤ Informe OT</button></div>
    ${open.some(x=>/alto|crítico/i.test(x.data.risk||''))?'<div class="callout danger section"><b>Trabajo con desviación de riesgo alto o crítico abierta.</b> Debe verificarse antes del cierre.</div>':''}
    <h2>Avances (${prog.length})</h2><div class="list">${prog.length?prog.slice().reverse().map(recordItem).join(''):empty('Sin avances registrados.')}</div><h2>Seguridad (${saf.length})</h2><div class="list">${saf.length?saf.slice().reverse().map(recordItem).join(''):empty('Sin desviaciones registradas.')}</div><h2>Evaluaciones (${kpi.length})</h2><div class="list">${kpi.length?kpi.slice().reverse().map(recordItem).join(''):empty('Sin evaluaciones registradas.')}</div>`
  }
  function recordItem(x){const risk=x.data?.risk||'',photo=x.photo?'<span class="badge blue">📷 Foto</span>':'';return `<div class="list-item ${/alto|crítico/i.test(risk)?'risk-high':/medio/i.test(risk)?'risk-medium':''}"><div class="line"><b>${esc(titleFor(x))}</b><span>${photo}${risk?badge(risk,riskClass(risk)):''}</span></div><div class="meta">${fmt(x.at)}${x.data?.action?' · Acción: '+esc(x.data.action):''}</div></div>`}
  function jobOptions(selected=''){return list('job').slice().reverse().map(j=>`<option value="${j.id}" ${j.id===selected?'selected':''}>${esc(j.data.folio)} · ${esc(j.data.equip)}</option>`).join('')}
  function progressForm(){const selected=state.jobId||activeJobs()[0]?.id||'';return `<span class="eyebrow">Registro rápido</span><h1>Avance de trabajo</h1><form id="record-form" data-form="progress"><label>Orden de trabajo<select name="jobId" required><option value="">Selecciona OT</option>${jobOptions(selected)}</select></label><label>Avance total (%)<input name="percent" type="number" min="0" max="100" value="0" required></label><label>Actividad realizada<textarea name="text" required placeholder="Puedes usar el dictado del teclado del teléfono"></textarea></label><label>Hallazgos técnicos<textarea name="findings" placeholder="Mediciones, desgaste, anomalías o pendientes"></textarea></label><label>Tipo de fotografía<select name="photoType"><option>Durante el trabajo</option><option>Hallazgo</option><option>Antes</option><option>Después</option></select></label><button type="button" class="outline" data-photo>📷 Tomar o adjuntar fotografía</button><div id="photo-preview"></div><button class="primary">Guardar avance</button></form>`}
  function safetyForm(){const selected=state.jobId||'',walk=state.walkId||'';return `<span class="eyebrow">Seguridad</span><h1>Registrar desviación</h1><form id="record-form" data-form="safety"><label>Origen<select name="origin"><option ${selected?'selected':''}>Trabajo</option><option ${walk?'selected':''}>Caminata</option><option ${!selected&&!walk?'selected':''}>Independiente</option></select></label><label>Orden de trabajo (opcional)<select name="jobId"><option value="">Sin OT asociada</option>${jobOptions(selected)}</select></label><input type="hidden" name="walkId" value="${esc(walk)}"><div class="grid"><label>Planta<input name="plant" required></label><label>Área / ubicación<input name="area" required></label></div><label>Categoría<select name="category"><option>Condición insegura</option><option>Conducta insegura</option><option>Control crítico</option><option>LOTO / energías peligrosas</option><option>Orden y aseo</option><option>EPP</option><option>Izaje</option><option>Trabajo en altura</option><option>Línea de fuego</option><option>Observación positiva</option></select></label><label>Nivel de riesgo<select name="risk"><option>Bajo</option><option>Medio</option><option>Alto</option><option>Crítico</option></select></label><label>Descripción objetiva<textarea name="text" required></textarea></label><label>Acción inmediata<textarea name="action" placeholder="Qué se hizo para controlar el riesgo"></textarea></label><label>Medida correctiva / consejo de solución<textarea name="recommendation" placeholder="Prioriza eliminación, ingeniería y controles administrativos antes del EPP"></textarea></label><div class="grid"><label>Responsable<input name="responsible"></label><label>Fecha compromiso<input name="dueDate" type="date"></label></div><label>Tipo de fotografía<select name="photoType"><option>Evidencia de desviación</option><option>Evidencia de corrección</option><option>Observación positiva</option></select></label><button type="button" class="outline" data-photo>📷 Tomar o adjuntar fotografía</button><div id="photo-preview"></div><button class="primary">Guardar desviación</button></form>`}
  function safety(){const s=list('safety').slice().reverse(),w=list('walk').slice().reverse();return `<h1>Seguridad</h1><div class="grid"><button class="quick" data-go="safety_new"><b>⚠</b>Nueva desviación</button><button class="quick" data-go="walk_new"><b>◉</b>Iniciar caminata</button></div><h2>Desviaciones</h2><div class="list">${s.length?s.map(recordItem).join(''):empty('No hay desviaciones registradas.')}</div><h2>Caminatas</h2><div class="list">${w.length?w.map(x=>`<button class="list-item" data-open-walk="${x.id}"><div class="line"><b>${esc(x.data.area)}</b>${badge(x.data.endAt?'Finalizada':'En curso',x.data.endAt?'green':'blue')}</div><div class="meta">${fmt(x.data.startAt)}</div></button>`).join(''):empty('No hay caminatas registradas.')}</div>`}
  function walkForm(){return `<span class="eyebrow">Seguridad en planta</span><h1>Iniciar caminata</h1><form id="record-form" data-form="walk"><label>Planta<input name="plant" required></label><label>Áreas o sectores a recorrer<input name="area" required></label><label>Objetivo<textarea name="objective" placeholder="Inspección preventiva, liderazgo, verificación de acciones..."></textarea></label><label>Participantes<input name="participants" value="${esc(C.supervisor)}"></label><button class="primary">Iniciar caminata ahora</button></form>`}
  function walkDetail(){const w=find(state.walkId);if(!w)return empty('Caminata no disponible.');const obs=list('safety').filter(x=>x.data.walkId===w.id);return `<span class="eyebrow">Caminata de seguridad</span><h1>${esc(w.data.area)}</h1><div class="hero"><p>${esc(w.data.plant)} · ${esc(w.data.objective||'Sin objetivo informado')}</p><p><b>Inicio:</b> ${fmt(w.data.startAt)}<br><b>Término:</b> ${fmt(w.data.endAt)}</p></div><div class="button-row section no-print"><button data-walk-go="safety_new">＋ Agregar hallazgo</button><button data-action="walk-end" class="primary" ${w.data.endAt?'disabled':''}>Finalizar caminata</button></div><h2>Hallazgos (${obs.length})</h2><div class="list">${obs.length?obs.slice().reverse().map(recordItem).join(''):empty('Registra desviaciones u observaciones positivas durante el recorrido.')}</div>`}
  function kpiForm(){const selected=state.jobId||'',techs=list('technician');return `<span class="eyebrow">Desempeño responsable</span><h1>Evaluación del técnico</h1><form id="record-form" data-form="kpi"><label>Orden de trabajo<select name="jobId" required><option value="">Selecciona OT</option>${jobOptions(selected)}</select></label><label>Técnico<input name="technician" list="tech-list" required><datalist id="tech-list">${techs.map(t=>`<option value="${esc(t.data.name)}">`).join('')}</datalist></label><p class="muted">Evalúa de 1 a 5. Seguridad y calidad tienen mayor peso; la rapidez nunca compensa una práctica insegura.</p><div class="grid"><label>Seguridad y controles críticos (30%)<input name="safety" type="number" min="1" max="5" value="5"></label><label>Calidad técnica (25%)<input name="quality" type="number" min="1" max="5" value="5"></label><label>Cumplimiento (15%)<input name="compliance" type="number" min="1" max="5" value="5"></label><label>Productividad responsable (10%)<input name="productivity" type="number" min="1" max="5" value="5"></label><label>Documentación (10%)<input name="documentation" type="number" min="1" max="5" value="5"></label><label>Coordinación (10%)<input name="communication" type="number" min="1" max="5" value="5"></label></div><label class="check"><input name="firstTimeRight" type="checkbox"> Trabajo correcto a la primera</label><label class="check"><input name="rework" type="checkbox"> Existió retrabajo</label><label class="check"><input name="externalFactors" type="checkbox"> Factores externos afectaron el resultado</label><label>Fortalezas y observaciones<textarea name="notes"></textarea></label><label>Capacitación requerida<textarea name="training"></textarea></label><button class="primary">Guardar evaluación</button></form>`}
  function score(d){return Math.round(((+d.safety*.30)+(+d.quality*.25)+(+d.compliance*.15)+(+d.productivity*.10)+(+d.documentation*.10)+(+d.communication*.10))/5*100)}
  function reports(){const today=dateKey();return `<h1>Informes</h1><form id="report-form"><label>Fecha del informe diario<input name="date" type="date" value="${today}"></label><button class="primary">Generar informe general diario</button></form><h2>Informes por trabajo</h2><div class="list">${list('job').length?list('job').slice().reverse().map(j=>`<button class="list-item" data-report-job="${j.id}"><b>${esc(j.data.folio)} · ${esc(j.data.equip)}</b><div class="meta">Inicio real: ${fmt(j.data.actualStart)} · Término real: ${fmt(j.data.actualEnd)}</div></button>`).join(''):empty('No hay trabajos para informar.')}</div>`}
  function photosFor(jobId){return [...linked('progress',jobId),...linked('safety',jobId),find(jobId)].filter(Boolean).filter(x=>x.photo)}
  function jobReport(){const j=find(state.jobId);if(!j)return empty('Orden no disponible.');const d=j.data,prog=linked('progress',j.id),saf=linked('safety',j.id),kpis=linked('kpi',j.id),photos=photosFor(j.id);return `<article class="report-sheet"><span class="eyebrow">Informe técnico de mantención</span><h1>${esc(d.folio)} · ${esc(d.equip)}</h1><p><b>Supervisor:</b> ${esc(C.supervisor)}<br><b>Planta/Área:</b> ${esc(d.plant)} / ${esc(d.area)}<br><b>Trabajo:</b> ${esc(d.task)}<br><b>Estado:</b> ${esc(jobStatus(j))}<br><b>Fecha y hora de emisión:</b> ${fmt(iso())}</p><h2>Horario real y tiempos</h2><table class="report-table"><tr><th>Concepto</th><th>Inicio</th><th>Término</th><th>Duración</th></tr><tr><td>Documentación de seguridad</td><td>${fmt(d.docsStart)}</td><td>${fmt(d.docsEnd)}</td><td>${duration(d.docsStart,d.docsEnd)}</td></tr><tr><td>Bloqueo / aislamiento LOTO</td><td>${fmt(d.lotoStart)}</td><td>${fmt(d.lotoEnd)}</td><td>${duration(d.lotoStart,d.lotoEnd)}</td></tr><tr><td>Ejecución real del trabajo</td><td>${fmt(d.actualStart)}</td><td>${fmt(d.actualEnd)}</td><td>${netDuration(j)}</td></tr></table><p><b>Verificación de energía cero:</b> ${fmt(d.zeroVerifiedAt)}<br><b>Pausas:</b> ${durationMs(pauseMs(j))}<br><b>Avance final:</b> ${Number(d.progress||0)}%</p><h2>Actividades realizadas</h2>${prog.length?`<table class="report-table"><tr><th>Hora</th><th>Avance</th><th>Actividad / hallazgos</th></tr>${prog.map(x=>`<tr><td>${fmt(x.at)}</td><td>${esc(x.data.percent)}%</td><td>${esc(x.data.text)}${x.data.findings?'<br><b>Hallazgo:</b> '+esc(x.data.findings):''}</td></tr>`).join('')}</table>`:empty('No informado.')}<h2>Desviaciones de seguridad</h2>${saf.length?`<table class="report-table"><tr><th>Riesgo</th><th>Hallazgo</th><th>Acción / recomendación</th></tr>${saf.map(x=>`<tr><td>${esc(x.data.risk)}</td><td>${esc(x.data.category)}: ${esc(x.data.text)}</td><td>${esc(x.data.action||'No informada')}<br>${esc(x.data.recommendation||'')}</td></tr>`).join('')}</table>`:empty('No se registraron desviaciones para esta OT.')}<h2>Evaluación de técnicos</h2>${kpis.length?kpis.map(x=>`<div class="card"><b>${esc(x.data.technician)} · ${x.data.score}%</b><p>${esc(x.data.notes||'Sin observaciones.')}</p></div>`).join(''):empty('No informado.')}<h2>Registro fotográfico</h2><div class="grid">${photos.length?photos.map(x=>`<figure><img class="photo-preview" src="${x.photo}" alt="Evidencia ${esc(x.data?.photoType||x.type)}"><figcaption><b>${esc(x.data?.photoType||'Evidencia')}</b><br><small>${fmt(x.at)} · ${esc(titleFor(x))}</small></figcaption></figure>`).join(''):empty('No se adjuntaron fotografías.')}</div><p class="muted">Este informe utiliza exclusivamente antecedentes registrados en terreno. Los datos faltantes se indican como “No registrado”.</p><button class="primary no-print" data-print>Imprimir / guardar PDF</button></article>`}
  function dailyReport(){const day=state.reportDate||dateKey(),all=records().filter(x=>dateKey(x.data?.actualStart||x.data?.startAt||x.at)===day),jobs=all.filter(x=>x.type==='job'),saf=all.filter(x=>x.type==='safety'),walk=all.filter(x=>x.type==='walk'),kpis=all.filter(x=>x.type==='kpi'),completed=jobs.filter(x=>x.data.actualEnd),hh=jobs.reduce((n,j)=>{if(!j.data.actualStart||!j.data.actualEnd)return n;return n+Math.max(0,new Date(j.data.actualEnd)-new Date(j.data.actualStart)-pauseMs(j))/3600000*Math.max(1,String(j.data.technicians||'').split(',').filter(Boolean).length)},0);return `<article class="report-sheet"><span class="eyebrow">Informe general diario</span><h1>${new Date(day+'T12:00:00').toLocaleDateString('es-CL',{dateStyle:'full'})}</h1><p><b>Supervisor:</b> ${esc(C.supervisor)}<br><b>Emitido:</b> ${fmt(iso())}</p><div class="grid stats"><div class="card"><small>Trabajos</small><b>${jobs.length}</b></div><div class="card"><small>Terminados</small><b>${completed.length}</b></div><div class="card"><small>Horas hombre</small><b>${hh.toFixed(1)}</b></div><div class="card"><small>Desviaciones</small><b>${saf.length}</b></div></div><h2>Consolidado de trabajos</h2>${jobs.length?`<table class="report-table"><tr><th>OT</th><th>Equipo</th><th>Inicio real</th><th>Término real</th><th>Avance</th></tr>${jobs.map(j=>`<tr><td>${esc(j.data.folio)}</td><td>${esc(j.data.equip)}</td><td>${fmt(j.data.actualStart)}</td><td>${fmt(j.data.actualEnd)}</td><td>${Number(j.data.progress||0)}%</td></tr>`).join('')}</table>`:empty('Sin trabajos registrados para la fecha.')}<h2>Seguridad y caminatas</h2><p>Caminatas: <b>${walk.length}</b> · Desviaciones abiertas: <b>${saf.filter(x=>!x.data.closedAt).length}</b> · Riesgos altos/críticos: <b>${saf.filter(x=>/alto|crítico/i.test(x.data.risk||'')).length}</b></p>${saf.length?`<table class="report-table"><tr><th>Origen</th><th>Área</th><th>Riesgo</th><th>Hallazgo / acción</th></tr>${saf.map(x=>`<tr><td>${esc(x.data.origin)}</td><td>${esc(x.data.area)}</td><td>${esc(x.data.risk)}</td><td>${esc(x.data.text)}<br>${esc(x.data.action||'')}</td></tr>`).join('')}</table>`:''}<h2>Evaluaciones KPI</h2><p>Evaluaciones: <b>${kpis.length}</b> · Promedio: <b>${kpis.length?Math.round(kpis.reduce((n,x)=>n+(+x.data.score||0),0)/kpis.length):'No informado'}${kpis.length?'%':''}</b></p><p class="muted">La fecha de emisión no modifica las horas reales de ejecución registradas.</p><button class="primary no-print" data-print>Imprimir / guardar PDF</button></article>`}
  function technicianForm(){return `<span class="eyebrow">Personal</span><h1>Registrar técnico</h1><form id="record-form" data-form="technician"><label>Nombre completo<input name="name" required></label><label>Especialidad<select name="specialty"><option>Mecánico</option><option>Eléctrico</option><option>Instrumentista</option><option>Piping</option><option>Calidad</option><option>Prevención</option><option>Otra</option></select></label><label>Empresa<input name="company"></label><button class="primary">Guardar técnico</button></form>`}
  function kpiOverview(){const a=list('kpi'),groups={};a.forEach(x=>(groups[x.data.technician]??=[]).push(x));return `<h1>KPI de técnicos</h1><div class="callout"><b>Criterio responsable:</b> seguridad 30%, calidad 25%, cumplimiento 15%, productividad 10%, documentación 10% y coordinación 10%.</div><div class="list section">${Object.keys(groups).length?Object.entries(groups).map(([name,v])=>{const avg=Math.round(v.reduce((n,x)=>n+(+x.data.score||0),0)/v.length);return `<div class="list-item"><div class="line"><b>${esc(name)}</b><span class="kpi-score">${avg}%</span></div><div class="meta">${v.length} evaluación(es) · Retrabajos: ${v.filter(x=>x.data.rework).length} · Correcto a la primera: ${v.filter(x=>x.data.firstTimeRight).length}</div></div>`}).join(''):empty('No hay evaluaciones todavía.')}</div>`}
  function more(){return `<h1>Más opciones</h1><div class="stack"><button id="install" class="primary">Instalar MANTPRO en este equipo</button><button id="guide" class="outline">Ver guía de instalación</button><button data-go="technician_new">Registrar técnico</button><button data-go="kpi_overview">Evaluación y KPI</button><button id="choose-backup">Elegir carpeta de respaldos</button><button id="backup">Crear respaldo ahora</button><button id="restore">Restaurar respaldo</button><button id="sync-now">Sincronizar ahora</button><button id="signout" class="outline">Desvincular este dispositivo</button><button id="reset" class="danger">Respaldar y borrar todos los datos</button><div class="callout"><b>Cuenta autorizada:</b> ${esc(C.allowedEmail)}<br><b>Supervisor:</b> ${esc(C.supervisor)}<br><b>Nube:</b> Supabase Cloud</div></div>`}
  function render(){top();const m=$('#app');const views={home,jobs,job_new:jobForm,job_detail:jobDetail,progress_new:progressForm,safety,safety_new:safetyForm,walk_new:walkForm,walk_detail:walkDetail,kpi_new:kpiForm,reports,job_report:jobReport,daily_report:dailyReport,technician_new:technicianForm,kpi_overview:kpiOverview,more};m.innerHTML=(views[state.route]||home)();bind()}
  function bind(){
    $$('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-open-job]').forEach(b=>b.onclick=()=>go('job_detail',{jobId:b.dataset.openJob}));$$('[data-open-walk]').forEach(b=>b.onclick=()=>go('walk_detail',{walkId:b.dataset.openWalk}));$$('[data-job-go]').forEach(b=>b.onclick=()=>go(b.dataset.jobGo,{jobId:state.jobId}));$$('[data-walk-go]').forEach(b=>b.onclick=()=>go(b.dataset.walkGo,{walkId:state.walkId}));$$('[data-report-job]').forEach(b=>b.onclick=()=>go('job_report',{jobId:b.dataset.reportJob}));$$('[data-action]').forEach(b=>b.onclick=()=>jobAction(b.dataset.action));$$('[data-print]').forEach(b=>b.onclick=()=>print());
    const f=$('#record-form');if(f)f.onsubmit=saveForm;const rf=$('#report-form');if(rf)rf.onsubmit=e=>{e.preventDefault();state.reportDate=new FormData(rf).get('date');go('daily_report')};
    const photo=$('[data-photo]');if(photo)photo.onclick=()=>$('#photo').click();
    $('#sync-now')?.addEventListener('click',sync);$('#signout')?.addEventListener('click',()=>window.MANTPRO_AUTH.signOut());$('#backup')?.addEventListener('click',createBackup);$('#choose-backup')?.addEventListener('click',chooseBackupFolder);$('#restore')?.addEventListener('click',()=>$('#restore-file').click());$('#reset')?.addEventListener('click',resetAll);$('#install')?.addEventListener('click',installApp);$('#guide')?.addEventListener('click',()=>location.href='instalar.html');
  }
  async function saveForm(e){
    e.preventDefault();const form=e.currentTarget,type=form.dataset.form,d=Object.fromEntries(new FormData(form));
    if(type==='job'){['plannedStart','plannedEnd'].forEach(k=>{if(d[k])d[k]=new Date(d[k]).toISOString()});d.progress=0;d.pauses=[];const x=add('job',`${d.folio} · ${d.equip}`,d);if(state.photo){x.photo=state.photo;upsert(x)}toast('Orden guardada');go('job_detail',{jobId:x.id});return}
    if(type==='progress'){const job=find(d.jobId);if(!job)return toast('Selecciona una OT');d.percent=Math.max(0,Math.min(100,+d.percent||0));const x=add('progress',`${d.percent}% · ${d.text}`,d);if(state.photo){x.photo=state.photo;upsert(x)}job.data.progress=d.percent;upsert(job);toast('Avance guardado');go('job_detail',{jobId:d.jobId});return}
    if(type==='safety'){const x=add('safety',`${d.category} · ${d.area}`,d);if(state.photo){x.photo=state.photo;upsert(x)}toast('Desviación guardada');if(d.jobId)go('job_detail',{jobId:d.jobId});else if(d.walkId)go('walk_detail',{walkId:d.walkId});else go('safety');return}
    if(type==='walk'){d.startAt=iso();const x=add('walk',`Caminata · ${d.area}`,d);toast('Caminata iniciada');go('walk_detail',{walkId:x.id});return}
    if(type==='kpi'){['firstTimeRight','rework','externalFactors'].forEach(k=>d[k]=new FormData(form).has(k));d.score=score(d);add('kpi',`${d.technician} · ${d.score}%`,d);toast('Evaluación guardada');go('job_detail',{jobId:d.jobId});return}
    if(type==='technician'){add('technician',d.name,d);toast('Técnico registrado');go('more')}
  }
  function jobAction(action){
    const j=find(state.jobId);if(!j)return;const d=j.data,t=iso();
    if(action==='docs-start')d.docsStart=t;if(action==='docs-end')d.docsEnd=t;if(action==='loto-start')d.lotoStart=t;if(action==='zero')d.zeroVerifiedAt=t;if(action==='loto-end')d.lotoEnd=t;
    if(action==='work-start')d.actualStart=t;
    if(action==='pause')d.pauseStartAt=t;
    if(action==='resume'){d.pauses=d.pauses||[];d.pauses.push({start:d.pauseStartAt,end:t});d.pauseStartAt=null}
    if(action==='work-end'){
      const critical=linked('safety',j.id).some(x=>!x.data.closedAt&&/alto|crítico/i.test(x.data.risk||''));if(critical){alert('No se puede finalizar: existe una desviación de riesgo alto o crítico sin cierre verificado.');return}
      if(d.pauseStartAt){d.pauses=d.pauses||[];d.pauses.push({start:d.pauseStartAt,end:t});d.pauseStartAt=null}d.actualEnd=t;if(Number(d.progress)<100&&confirm('¿Marcar el avance como 100%?'))d.progress=100;
    }
    if(action==='walk-end'){const w=find(state.walkId);w.data.endAt=t;upsert(w);render();toast('Caminata finalizada');return}
    upsert(j);render();toast('Hora registrada: '+time(t))
  }
  async function imageData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onload=()=>{const max=1280,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.78))};img.onerror=reject;img.src=reader.result};reader.readAsDataURL(file)})}
  async function handlePhoto(e){const file=e.target.files?.[0];if(!file)return;try{state.photo=await imageData(file);const p=$('#photo-preview');if(p)p.innerHTML=`<div class="photo-note">✓ Fotografía preparada</div><img class="photo-preview" src="${state.photo}" alt="Vista previa">`;toast('Fotografía adjunta')}catch{toast('No fue posible leer la fotografía')}finally{e.target.value=''}}
  function backupPayload(){return{application:'MANTPRO IA Cloud',version:'3.1',supervisor:C.supervisor,exportedAt:iso(),records:records()}}
  function downloadBackup(){const data=JSON.stringify(backupPayload(),null,2),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download='MANTPRO_IA_Respaldo_'+iso().replace(/[:.]/g,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function idb(){return new Promise((res,rej)=>{const q=indexedDB.open('mantpro-settings',1);q.onupgradeneeded=()=>q.result.createObjectStore('settings');q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
  async function saveHandle(h){const db=await idb();return new Promise((res,rej)=>{const t=db.transaction('settings','readwrite'),q=t.objectStore('settings').put(h,'backup-directory');q.onsuccess=res;q.onerror=()=>rej(q.error)})}
  async function getHandle(){const db=await idb();return new Promise((res,rej)=>{const q=db.transaction('settings').objectStore('settings').get('backup-directory');q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
  async function chooseBackupFolder(){if(!window.showDirectoryPicker){downloadBackup();toast('El navegador descargó el respaldo. Puedes moverlo a tu carpeta anual.');return}try{const h=await showDirectoryPicker({mode:'readwrite'});await saveHandle(h);toast('Carpeta de respaldo vinculada')}catch(err){if(err.name!=='AbortError')toast('No fue posible vincular la carpeta')}}
  async function createBackup(){
    if(window.showDirectoryPicker)try{let h=await getHandle();if(!h){await chooseBackupFolder();h=await getHandle()}if(h){const p=await h.queryPermission({mode:'readwrite'});if(p!=='granted'&&await h.requestPermission({mode:'readwrite'})!=='granted')throw Error('permiso');const d=new Date(),root=await h.getDirectoryHandle('Respaldos_MANTPRO_IA',{create:true}),year=await root.getDirectoryHandle(String(d.getFullYear()),{create:true}),month=await year.getDirectoryHandle(monthNames[d.getMonth()],{create:true}),file=await month.getFileHandle('MANTPRO_IA_Respaldo_'+iso().replace(/[:.]/g,'-')+'.json',{create:true}),w=await file.createWritable();await w.write(JSON.stringify(backupPayload(),null,2));await w.close();toast('Respaldo guardado por año y mes');return true}}catch(err){console.warn(err)}
    downloadBackup();toast('Respaldo descargado');return true
  }
  async function restoreFile(e){const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.records))throw Error();const map=new Map(records().map(x=>[x.id,x]));data.records.forEach(x=>map.set(x.id,{...x,dirty:true,synced:false,updatedAt:iso()}));persist([...map.values()]);toast('Respaldo restaurado');sync();render()}catch{alert('El archivo no corresponde a un respaldo válido de MANTPRO.')}finally{e.target.value=''}}
  async function resetAll(){if(!confirm('Primero se creará un respaldo. Luego se borrarán los datos locales y de la nube. ¿Continuar?'))return;await createBackup();const code=prompt('Escribe BORRAR para confirmar el reinicio total.');if(code!=='BORRAR')return;try{if(window.MANTPRO_AUTH?.token()){const r=await fetch(C.supabaseUrl+'/rest/v1/mantpro_records?id=not.is.null',{method:'DELETE'});if(!r.ok)throw Error(await r.text())}persist([]);toast('Datos eliminados. MANTPRO quedó en cero.');go('home')}catch{alert('No se completó el borrado en la nube. Los datos se conservaron para evitar una pérdida parcial.')}}
  async function installApp(){if(state.installPrompt){state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;toast('Instalación iniciada')}else alert('En computador: abre el menú del navegador y elige “Aplicaciones > Instalar este sitio”. En Android: menú ⋮ > Agregar a pantalla principal > Instalar.')}
  function back(){if(state.route==='job_detail'||state.route==='job_report')go('jobs');else if(state.route==='walk_detail')go('safety');else go(state.previous||'home')}
  function boot(){migrate();$('#back').onclick=back;$('#state').onclick=sync;$('#photo').onchange=handlePhoto;$('#restore-file').onchange=restoreFile;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e});window.addEventListener('online',sync);window.addEventListener('offline',()=>status('Sin señal · guardado local','warn'));window.addEventListener('mantpro-auth-ready',sync);window.addEventListener('mantpro-auth-changed',sync);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=7').catch(()=>{});render();sync();setInterval(()=>{if(!document.hidden)sync()},30000)}
  window.MANTPRO={records,render,sync};boot();
})();

