/* Vinculación por enlace mágico. La sesión se guarda en este dispositivo. */
(()=>{const C=window.MANTPRO_CONFIG||{},K='mantpro-session',base=C.supabaseUrl;
const get=()=>{try{return JSON.parse(localStorage.getItem(K)||'null')}catch{return null}},set=x=>localStorage.setItem(K,JSON.stringify(x));
function token(){let s=get();return s&&s.access_token}
const originalFetch=window.fetch.bind(window);window.fetch=(url,opt={})=>{if(typeof url==='string'&&base&&url.startsWith(base)){let h=new Headers(opt.headers||{});if(token())h.set('Authorization','Bearer '+token());h.set('apikey',C.supabaseAnonKey);opt={...opt,headers:h}}return originalFetch(url,opt)};
function overlay(){if(document.getElementById('auth'))return;document.body.insertAdjacentHTML('beforeend','<div id="auth" style="position:fixed;inset:0;z-index:20;display:grid;place-items:center;padding:20px;background:#15191ef5"><form id="authform" style="max-width:420px;width:100%;background:#20262d;border:1px solid #37414d;border-radius:14px;padding:24px;color:#f5f7f9;font:16px system-ui"><h2 style="margin-top:0">Vincular MANTPRO IA</h2><p style="color:#adb8c5">Ingresa tu correo. Recibirás un enlace seguro una sola vez en este dispositivo.</p><label style="display:grid;gap:7px;color:#adb8c5">Correo electrónico<input required type="email" name="email" placeholder="tu@correo.com" style="padding:12px;border-radius:9px;background:#15191e;color:white;border:1px solid #4a5664;font:inherit"></label><p id="authmsg" style="min-height:20px;color:#adb8c5"></p><button style="width:100%;padding:12px;background:#f68b1f;border:0;border-radius:9px;font-weight:800;font-size:16px">Enviar enlace de acceso</button></form></div>');document.getElementById('authform').onsubmit=login}
async function login(e){e.preventDefault();let email=String(new FormData(e.target).get('email')).trim().toLowerCase(),msg=document.getElementById('authmsg');if(C.allowedEmail&&email!==C.allowedEmail.toLowerCase()){msg.textContent='Este correo no está autorizado para MANTPRO IA.';return}msg.textContent='Enviando enlace…';try{let r=await originalFetch(base+'/auth/v1/otp',{method:'POST',headers:{apikey:C.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({email,create_user:true,options:{emailRedirectTo:location.href.split('#')[0]}})});if(!r.ok){let detail=await r.json().catch(()=>({}));throw Error(detail.msg||detail.message||('Error '+r.status))}msg.textContent='Revisa tu correo y abre el enlace para terminar la vinculación.'}catch(err){msg.textContent='No fue posible enviar el enlace: '+(err.message||'error desconocido')}}
function finish(){let h=new URLSearchParams(location.hash.slice(1));if(h.get('access_token')){set({access_token:h.get('access_token'),refresh_token:h.get('refresh_token'),expires_at:Date.now()+(+h.get('expires_in')||3600)*1000});history.replaceState({},'',location.pathname);document.getElementById('auth')?.remove();setTimeout(()=>window.sync&&window.sync(),100)}else if(!token())overlay()}
function enhance(){if(!window.sync)return setTimeout(enhance,50);let native=window.sync;window.sync=async()=>{await native();if(!token())return;try{let r=await originalFetch(base+'/rest/v1/mantpro_records?select=payload&order=occurred_at.asc');if(!r.ok)throw Error();let remote=await r.json(),local=window.get?window.get():JSON.parse(localStorage.getItem('mantpro-records')||'[]'),ids=new Set(local.map(x=>x.id));for(let x of remote){if(x.payload&&!ids.has(x.payload.id))local.push(x.payload)}localStorage.setItem('mantpro-records',JSON.stringify(local));window.render&&window.render()}catch(e){}}}
finish();enhance()})();